var markers = [];
var map;

$(document).ready(function() {  
  
    map = L.map('map-omninesia', {
        crs: L.CRS.Simple,
        attributionControl: false,
        minZoom: 1,
        preferCanvas: true
    });
  
  var bounds = [[0,0], [1000,1000]];
  var image = L.imageOverlay('images/maps/omninesia.png', bounds).addTo(map);
  map.fitBounds(bounds);
  
  L.control.mousePosition().addTo(map);

  var TemMarker = L.Icon.extend({
    options: {
        shadowUrl: '',
        iconSize:     [39, 51], // size of the icon
        shadowSize:   [0, 0], // size of the shadow
        iconAnchor:   [22, 51], // point of the icon which will correspond to marker's location
        shadowAnchor: [0, 0],  // the same for the shadow
        popupAnchor:  [19, 0], // point from which the popup should open relative to the iconAnchor
        tooltipAnchor: [24, -30]
    }
  });
  var npcGenericIcon = new TemMarker({iconUrl: 'images/icons/npc.png'});
  var npcMovingIcon = new TemMarker({iconUrl: 'images/icons/npc-moving.png'});
  var npcVendorIcon = new TemMarker({iconUrl: 'images/icons/npc-vendor.png'});
  var npcClothingIcon = new TemMarker({iconUrl: 'images/icons/npc-clothing.png'});
  var npcFurnitureIcon = new TemMarker({iconUrl: 'images/icons/npc-furniture.png'});
  var npcCombatIcon = new TemMarker({iconUrl: 'images/icons/npc-combat.png'});
  var npcMovingCombatIcon = new TemMarker({iconUrl: 'images/icons/npc-moving-combat.png'});
  var npcBreederIcon = new TemMarker({iconUrl: 'images/icons/npc-breeder.png'});
  var npcFruitIcon = new TemMarker({iconUrl: 'images/icons/npc-fruit.png'});
  var npcProfessorKonstantinosIcon = new TemMarker({iconUrl: 'images/icons/professor-konstantinos.png'});
  var npcAdiaTurayIcon = new TemMarker({iconUrl: 'images/icons/adia-turay.png'});
  var npcTihaniIcon = new TemMarker({iconUrl: 'images/icons/tihani.png'});  
  var npcRawiriIcon = new TemMarker({iconUrl: 'images/icons/rawiri.png'});  
  var npcFireGuardIcon = new TemMarker({iconUrl: 'images/icons/npc-fire-guard.png'});
  
  var bwanbale = L.marker([568.38, 302], {title: 'bwanbale', icon: npcGenericIcon}).bindTooltip('Bwanbale', {className: 'tooltip'}).addTo(map);
  bwanbale._icon.classList.add('bwanbale');
  markers.push(bwanbale);
  var touristinformation = L.marker([861.42, 797.22], {title: 'touristinformation', icon: npcMovingIcon}).bindTooltip('Tourist Information', {className: 'tooltip'}).addTo(map);
  touristinformation._icon.classList.add('touristinformation');
  touristinformation._icon.classList.add('moving');
  markers.push(touristinformation);
  var nangalocal = L.marker([865.04, 772.71], {title: 'nangalocal', icon: npcGenericIcon}).bindTooltip('Nanga Local', {className: 'tooltip'}).addTo(map);
  nangalocal._icon.classList.add('nangalocal');
  markers.push(nangalocal);
  var nakkiah = L.marker([855.64, 758.26], {title: 'nakkiah', icon: npcGenericIcon}).bindTooltip('Nakkiah', {className: 'tooltip'}).addTo(map);
  nakkiah._icon.classList.add('nakkiah');
  markers.push(nakkiah);
  var nanguitamer = L.marker([892.62, 709.13], {title: 'nanguitamer', icon: npcGenericIcon}).bindTooltip('Nangui Tamer', {className: 'tooltip'}).addTo(map);
  nanguitamer._icon.classList.add('nanguitamer');
  markers.push(nanguitamer);
  var mokupunitamer = L.marker([889.62, 711.75], {title: 'mokupunitamer', icon: npcGenericIcon}).bindTooltip('Mokupuni Tamer', {className: 'tooltip'}).addTo(map);
  mokupunitamer._icon.classList.add('mokupunitamer');
  markers.push(mokupunitamer);
  var newspaperboy = L.marker([905.92, 690.84], {title: 'newspaperboy', icon: npcMovingIcon}).bindTooltip('Newspaper Boy', {className: 'tooltip'}).addTo(map);
  newspaperboy._icon.classList.add('newspaperboy');
  newspaperboy._icon.classList.add('moving');
  markers.push(newspaperboy);
  var matelita = L.marker([902.58, 725.61], {title: 'matelita', icon: npcFurnitureIcon}).bindTooltip('Matelita', {className: 'tooltip'}).addTo(map);
  matelita._icon.classList.add('matelita');
  matelita._icon.classList.add('furniture');
  markers.push(matelita);
  var temporiumvendor = L.marker([933.68, 690.69], {title: 'temporiumvendor', icon: npcVendorIcon}).bindTooltip('Temporium Vendor', {className: 'tooltip'}).addTo(map);
  temporiumvendor._icon.classList.add('temporiumvendor');
  temporiumvendor._icon.classList.add('vendor');
  markers.push(temporiumvendor);
  var braggingtamer = L.marker([933.68, 692.69], {title: 'braggingtamer', icon: npcGenericIcon}).bindTooltip('Bragging Tamer', {className: 'tooltip'}).addTo(map);
  braggingtamer._icon.classList.add('braggingtamer');
  markers.push(braggingtamer);
  var chattytamer = L.marker([933.68, 689.69], {title: 'chattytamer', icon: npcGenericIcon}).bindTooltip('Chatty Tamer', {className: 'tooltip'}).addTo(map);
  chattytamer._icon.classList.add('chattytamer');
  markers.push(chattytamer);
  var elderlyomninesian = L.marker([875.31, 678.81], {title: 'elderlyomninesian', icon: npcGenericIcon}).bindTooltip('Elderly Omninesian', {className: 'tooltip'}).addTo(map);
  elderlyomninesian._icon.classList.add('elderlyomninesian');
  markers.push(elderlyomninesian);
  var indecisiveshopper = L.marker([881.56, 674.23], {title: 'indecisiveshopper', icon: npcMovingIcon}).bindTooltip('Indecisive Shopper', {className: 'tooltip'}).addTo(map);
  indecisiveshopper._icon.classList.add('indecisiveshopper');
  indecisiveshopper._icon.classList.add('moving');
  markers.push(indecisiveshopper);
  var nanguifashionista = L.marker([889.56, 658.35], {title: 'nanguifashionista', icon: npcGenericIcon}).bindTooltip('Nangui Fashionista', {className: 'tooltip'}).addTo(map);
  nanguifashionista._icon.classList.add('nanguifashionista');
  markers.push(nanguifashionista);
  var mahi = L.marker([906.68, 658.99], {title: 'mahi', icon: npcClothingIcon}).bindTooltip('Mahi', {className: 'tooltip'}).addTo(map);
  mahi._icon.classList.add('mahi');
  mahi._icon.classList.add('clothing');
  markers.push(mahi);
  var cluelessshopper = L.marker([906.68, 660.99], {title: 'cluelessshopper', icon: npcGenericIcon}).bindTooltip('Clueless Shopper', {className: 'tooltip'}).addTo(map);
  cluelessshopper._icon.classList.add('cluelessshopper');
  markers.push(cluelessshopper);
  var savvyshopper = L.marker([906.68, 662.99], {title: 'savvyshopper', icon: npcGenericIcon}).bindTooltip('Savvy Shopper', {className: 'tooltip'}).addTo(map);
  savvyshopper._icon.classList.add('savvyshopper');
  markers.push(savvyshopper);
  var civilengineer = L.marker([793.98, 738.12], {title: 'civilengineer', icon: npcGenericIcon}).bindTooltip('Civil Engineer', {className: 'tooltip'}).addTo(map);
  civilengineer._icon.classList.add('civilengineer');
  markers.push(civilengineer);
  var mele = L.marker([776.65, 738.76], {title: 'mele', icon: npcGenericIcon}).bindTooltip('Mele', {className: 'tooltip'}).addTo(map);
  mele._icon.classList.add('mele');
  markers.push(mele);
  var myrengreceptionist = L.marker([777.08, 720.01], {title: 'myrengreceptionist', icon: npcGenericIcon}).bindTooltip('MyrEng Receptionist', {className: 'tooltip'}).addTo(map);
  myrengreceptionist._icon.classList.add('myrengreceptionist');
  markers.push(myrengreceptionist);
  var taterubreeder = L.marker([779.08, 720.01], {title: 'taterubreeder', icon: npcGenericIcon}).bindTooltip('Tateru Breeder', {className: 'tooltip'}).addTo(map);
  taterubreeder._icon.classList.add('taterubreeder');
  markers.push(taterubreeder);
  var taterufan = L.marker([781.08, 720.01], {title: 'taterufan', icon: npcGenericIcon}).bindTooltip('Tateru Fan', {className: 'tooltip'}).addTo(map);
  taterufan._icon.classList.add('taterufan');
  markers.push(taterufan);
  var sleepytraveler = L.marker([783.08, 720.01], {title: 'sleepytraveler', icon: npcGenericIcon}).bindTooltip('Sleepy Traveler', {className: 'tooltip'}).addTo(map);
  sleepytraveler._icon.classList.add('sleepytraveler');
  markers.push(sleepytraveler);
  var skepticalwoman = L.marker([777.08, 715.01], {title: 'skepticalwoman', icon: npcGenericIcon}).bindTooltip('Skeptical Woman', {className: 'tooltip'}).addTo(map);
  skepticalwoman._icon.classList.add('skepticalwoman');
  markers.push(skepticalwoman);
  var windbag = L.marker([779.08, 715.01], {title: 'windbag', icon: npcGenericIcon}).bindTooltip('Windbag', {className: 'tooltip'}).addTo(map);
  windbag._icon.classList.add('windbag');
  markers.push(windbag);
  var foxytamer = L.marker([781.08, 715.01], {title: 'foxytamer', icon: npcGenericIcon}).bindTooltip('Foxy Tamer', {className: 'tooltip'}).addTo(map);
  foxytamer._icon.classList.add('foxytamer');
  markers.push(foxytamer);
  var taciturnlodger = L.marker([783.08, 715.01], {title: 'taciturnlodger', icon: npcGenericIcon}).bindTooltip('Taciturn Lodger', {className: 'tooltip'}).addTo(map);
  taciturnlodger._icon.classList.add('taciturnlodger');
  markers.push(taciturnlodger);
  var zeppelinlover = L.marker([785.08, 715.01], {title: 'zeppelinlover', icon: npcGenericIcon}).bindTooltip('Zeppelin Lover', {className: 'tooltip'}).addTo(map);
  zeppelinlover._icon.classList.add('zeppelinlover');
  markers.push(zeppelinlover);
  var restingtraveler = L.marker([785.08, 715.01], {title: 'restingtraveler', icon: npcGenericIcon}).bindTooltip('Resting Traveler', {className: 'tooltip'}).addTo(map);
  restingtraveler._icon.classList.add('restingtraveler');
  markers.push(restingtraveler);
  var strandedcaptain = L.marker([776.83, 694.01], {title: 'strandedcaptain', icon: npcGenericIcon}).bindTooltip('Stranded Captain', {className: 'tooltip'}).addTo(map);
  strandedcaptain._icon.classList.add('strandedcaptain');
  markers.push(strandedcaptain);
  var exasperatedtamer = L.marker([781.83, 694.01], {title: 'exasperatedtamer', icon: npcGenericIcon}).bindTooltip('Exasperated Tamer', {className: 'tooltip'}).addTo(map);
  exasperatedtamer._icon.classList.add('exasperatedtamer');
  markers.push(exasperatedtamer);
  var lodger = L.marker([786.83, 694.01], {title: 'lodger', icon: npcGenericIcon}).bindTooltip('Lodger', {className: 'tooltip'}).addTo(map);
  lodger._icon.classList.add('lodger');
  markers.push(lodger);
  var haplesswriter = L.marker([791.83, 694.01], {title: 'haplesswriter', icon: npcGenericIcon}).bindTooltip('Hapless Writer', {className: 'tooltip'}).addTo(map);
  haplesswriter._icon.classList.add('haplesswriter');
  markers.push(haplesswriter);
  var accountant = L.marker([776.83, 699.01], {title: 'accountant', icon: npcGenericIcon}).bindTooltip('Accountant', {className: 'tooltip'}).addTo(map);
  accountant._icon.classList.add('accountant');
  markers.push(accountant);
  var olianasassistant = L.marker([781.83, 699.01], {title: 'olianasassistant', icon: npcGenericIcon}).bindTooltip("Oliana's Assistant", {className: 'tooltip'}).addTo(map);
  olianasassistant._icon.classList.add('olianasassistant');
  markers.push(olianasassistant);
  var oliana = L.marker([786.83, 699.01], {title: 'oliana', icon: npcGenericIcon}).bindTooltip('Oliana', {className: 'tooltip'}).addTo(map);
  oliana._icon.classList.add('oliana');
  markers.push(oliana);
  var intern = L.marker([791.83, 699.01], {title: 'intern', icon: npcGenericIcon}).bindTooltip('Intern', {className: 'tooltip'}).addTo(map);
  intern._icon.classList.add('intern');
  markers.push(intern);
  var designer = L.marker([776.83, 704.01], {title: 'designer', icon: npcGenericIcon}).bindTooltip('Designer', {className: 'tooltip'}).addTo(map);
  designer._icon.classList.add('designer');
  markers.push(designer);
  var nanguitoddler = L.marker([877.53, 630.95], {title: 'nanguitoddler', icon: npcGenericIcon}).bindTooltip('Nangui Toddler', {className: 'tooltip'}).addTo(map);
  nanguitoddler._icon.classList.add('nanguitoddler');
  markers.push(nanguitoddler);
  var nanguigranny = L.marker([877.53, 628.2], {title: 'nanguigranny', icon: npcGenericIcon}).bindTooltip('Nangui Granny', {className: 'tooltip'}).addTo(map);
  nanguigranny._icon.classList.add('nanguigranny');
  markers.push(nanguigranny);
  var loali = L.marker([772.67, 605.43], {title: 'loali', icon: npcGenericIcon}).bindTooltip('Loali', {className: 'tooltip'}).addTo(map);
  loali._icon.classList.add('loali');
  markers.push(loali);
  var stargazer = L.marker([772.67, 609.56], {title: 'stargazer', icon: npcGenericIcon}).bindTooltip('StarGazer', {className: 'tooltip'}).addTo(map);
  stargazer._icon.classList.add('stargazer');
  markers.push(stargazer);
  var tupou = L.marker([816.94, 611.06], {title: 'tupou', icon: npcGenericIcon}).bindTooltip('Tupou', {className: 'tooltip'}).addTo(map);
  tupou._icon.classList.add('tupou');
  markers.push(tupou);
  var losa = L.marker([784.3, 570.8], {title: 'losa', icon: npcGenericIcon}).bindTooltip('Losa', {className: 'tooltip'}).addTo(map);
  losa._icon.classList.add('losa');
  markers.push(losa);
  var tarlae = L.marker([766.04, 642.69], {title: 'tarlae', icon: npcGenericIcon}).bindTooltip('Tarlae', {className: 'tooltip'}).addTo(map);
  tarlae._icon.classList.add('tarlae');
  markers.push(tarlae);
  var dojogirl = L.marker([875.21, 592.65], {title: 'dojogirl', icon: npcGenericIcon}).bindTooltip('Dojo Girl', {className: 'tooltip'}).addTo(map);
  dojogirl._icon.classList.add('dojogirl');
  markers.push(dojogirl);
  var oneeyedmatthew = L.marker([923.43, 599.05], {title: 'oneeyedmatthew', icon: npcCombatIcon}).bindTooltip('One-Eyed Matthew', {className: 'tooltip'}).addTo(map);
  oneeyedmatthew._icon.classList.add('oneeyedmatthew');
  oneeyedmatthew._icon.classList.add('combat');
  markers.push(oneeyedmatthew);
  var aulii = L.marker([932.69, 593.05], {title: 'aulii', icon: npcGenericIcon}).bindTooltip("Auli'i", {className: 'tooltip'}).addTo(map);
  aulii._icon.classList.add('aulii');
  markers.push(aulii);
  var filisione = L.marker([937.69, 593.05], {title: 'filisione', icon: npcCombatIcon}).bindTooltip('Filisione', {className: 'tooltip'}).addTo(map);
  filisione._icon.classList.add('filisione');
  oneeyedmatthew._icon.classList.add('combat');
  markers.push(filisione);
  var sione = L.marker([942.69, 593.05], {title: 'sione', icon: npcCombatIcon}).bindTooltip('Sione', {className: 'tooltip'}).addTo(map);
  sione._icon.classList.add('sione');
  sione._icon.classList.add('combat');
  markers.push(sione);
  var vaitiar = L.marker([947.69, 593.05], {title: 'vaitiar', icon: npcCombatIcon}).bindTooltip('Vaitiaré', {className: 'tooltip'}).addTo(map);
  vaitiar._icon.classList.add('vaitiar');
  vaitiar._icon.classList.add('combat');
  markers.push(vaitiar);
  var taliauli = L.marker([932.69, 598.05], {title: 'taliauli', icon: npcCombatIcon}).bindTooltip("Talia'uli", {className: 'tooltip'}).addTo(map);
  taliauli._icon.classList.add('taliauli');
  taliauli._icon.classList.add('combat');
  markers.push(taliauli);
  var hoku = L.marker([937.69, 598.05], {title: 'hoku', icon: npcCombatIcon}).bindTooltip('Hoku', {className: 'tooltip'}).addTo(map);
  hoku._icon.classList.add('hoku');
  hoku._icon.classList.add('combat');
  markers.push(hoku);
  var tihani = L.marker([942.69, 598.05], {title: 'tihani', icon: npcTihaniIcon}).bindTooltip('Tihani', {className: 'tooltip'}).addTo(map);
  tihani._icon.classList.add('tihani');
  tihani._icon.classList.add('combat');
  markers.push(tihani);
  var maata = L.marker([887.97, 546.21], {title: 'maata', icon: npcCombatIcon}).bindTooltip('Maata', {className: 'tooltip'}).addTo(map);
  maata._icon.classList.add('maata');
  maata._icon.classList.add('combat');
  markers.push(maata);
  var temtivist = L.marker([907.48, 486.7], {title: 'temtivist', icon: npcGenericIcon}).bindTooltip('Temtivist', {className: 'tooltip'}).addTo(map);
  temtivist._icon.classList.add('temtivist');
  markers.push(temtivist);
  var freetemcoordinator = L.marker([930.74, 498.71], {title: 'freetemcoordinator', icon: npcGenericIcon}).bindTooltip('FreeTem! Coordinator', {className: 'tooltip'}).addTo(map);
  freetemcoordinator._icon.classList.add('freetemcoordinator');
  markers.push(freetemcoordinator);
  var freetemmanager = L.marker([925.74, 498.71], {title: 'freetemmanager', icon: npcGenericIcon}).bindTooltip('FreeTem! Manager', {className: 'tooltip'}).addTo(map);
  freetemmanager._icon.classList.add('freetemmanager');
  markers.push(freetemmanager);
  var temtembreeder = L.marker([951.21, 529.46], {title: 'temtembreeder', icon: npcBreederIcon}).bindTooltip('Temtem Breeder', {className: 'tooltip'}).addTo(map);
  temtembreeder._icon.classList.add('temtembreeder');
  temtembreeder._icon.classList.add('breeder');
  markers.push(temtembreeder);
  var breecenshopkeeper = L.marker([956.21, 529.46], {title: 'breecenshopkeeper', icon: npcBreederIcon}).bindTooltip('BreeCen Shopkeeper', {className: 'tooltip'}).addTo(map);
  breecenshopkeeper._icon.classList.add('breecenshopkeeper');
  breecenshopkeeper._icon.classList.add('breeder');
  markers.push(breecenshopkeeper);
  var fateia = L.marker([874.7, 489.96], {title: 'fateia', icon: npcCombatIcon}).bindTooltip('Fateia', {className: 'tooltip'}).addTo(map);
  fateia._icon.classList.add('fateia');
  fateia._icon.classList.add('combat');
  markers.push(fateia);
  var siosaia = L.marker([852.43, 468.46], {title: 'siosaia', icon: npcCombatIcon}).bindTooltip('Siosaia', {className: 'tooltip'}).addTo(map);
  siosaia._icon.classList.add('siosaia');
  siosaia._icon.classList.add('combat');
  markers.push(siosaia);
  var leilani = L.marker([806.71, 477.31], {title: 'leilani', icon: npcGenericIcon}).bindTooltip('Leilani', {className: 'tooltip'}).addTo(map);
  leilani._icon.classList.add('leilani');
  markers.push(leilani);
  var vea = L.marker([790.2, 553.07], {title: 'vea', icon: npcCombatIcon}).bindTooltip('Vea?', {className: 'tooltip'}).addTo(map);
  vea._icon.classList.add('vea');
  vea._icon.classList.add('combat');
  markers.push(vea);
  var mea = L.marker([785.7, 553.07], {title: 'mea', icon: npcCombatIcon}).bindTooltip('Mea?', {className: 'tooltip'}).addTo(map);
  mea._icon.classList.add('mea');
  mea._icon.classList.add('combat');
  markers.push(mea);
  var jordi = L.marker([768.11, 534.74], {title: 'jordi', icon: npcCombatIcon}).bindTooltip('Jordi', {className: 'tooltip'}).addTo(map);
  jordi._icon.classList.add('jordi');
  jordi._icon.classList.add('combat');
  markers.push(jordi);
  var koen = L.marker([768.11, 390.21], {title: 'koen', icon: npcCombatIcon}).bindTooltip('Koen', {className: 'tooltip'}).addTo(map);
  koen._icon.classList.add('koen');
  koen._icon.classList.add('combat');
  markers.push(koen);
  var taika = L.marker([795.6, 373.06], {title: 'taika', icon: npcCombatIcon}).bindTooltip('Taika', {className: 'tooltip'}).addTo(map);
  taika._icon.classList.add('taika');
  taika._icon.classList.add('combat');
  markers.push(taika);
  var waruu = L.marker([796.72, 374.69], {title: 'waruu', icon: npcCombatIcon}).bindTooltip('Waruu', {className: 'tooltip'}).addTo(map);
  waruu._icon.classList.add('waruu');
  waruu._icon.classList.add('combat');
  markers.push(waruu);
  var maka = L.marker([862.61, 378.06], {title: 'maka', icon: npcCombatIcon}).bindTooltip('Maka', {className: 'tooltip'}).addTo(map);
  maka._icon.classList.add('maka');
  maka._icon.classList.add('combat');
  markers.push(maka);
  var tamala = L.marker([919.05, 430.12], {title: 'tamala', icon: npcMovingCombatIcon}).bindTooltip('Tamala', {className: 'tooltip'}).addTo(map);
  tamala._icon.classList.add('tamala');
  tamala._icon.classList.add('moving');
  tamala._icon.classList.add('combat');
  markers.push(tamala);
  var fruitpicker2 = L.marker([926.47, 372.49], {title: 'fruitpicker2', icon: npcGenericIcon}).bindTooltip('Fruit Picker 2', {className: 'tooltip'}).addTo(map);
  fruitpicker2._icon.classList.add('fruitpicker2');
  markers.push(fruitpicker2);
  var tuki = L.marker([929.98, 375.49], {title: 'tuki', icon: npcGenericIcon}).bindTooltip('Tuki', {className: 'tooltip'}).addTo(map);
  tuki._icon.classList.add('tuki');
  markers.push(tuki);
  var fruitpicker1 = L.marker([944.23, 399.99], {title: 'fruitpicker1', icon: npcGenericIcon}).bindTooltip('Fruit Picker 1', {className: 'tooltip'}).addTo(map);
  fruitpicker1._icon.classList.add('fruitpicker1');
  markers.push(fruitpicker1);
  var visesiafanboy = L.marker([800.23, 346.36], {title: 'visesiafanboy', icon: npcGenericIcon}).bindTooltip('Visesia Fanboy', {className: 'tooltip'}).addTo(map);
  visesiafanboy._icon.classList.add('visesiafanboy');
  markers.push(visesiafanboy);
  var ukamalover = L.marker([799.6, 314.86], {title: 'ukamalover', icon: npcGenericIcon}).bindTooltip('Ukama Lover', {className: 'tooltip'}).addTo(map);
  ukamalover._icon.classList.add('ukamalover');
  markers.push(ukamalover);
  var retireddojomaster = L.marker([884.73, 302.1], {title: 'retireddojomaster', icon: npcGenericIcon}).bindTooltip('Retired Dojo Master', {className: 'tooltip'}).addTo(map);
  retireddojomaster._icon.classList.add('retireddojomaster');
  markers.push(retireddojomaster);
  var lazyvillager = L.marker([906.12, 313.86], {title: 'lazyvillager', icon: npcGenericIcon}).bindTooltip('Lazy Villager', {className: 'tooltip'}).addTo(map);
  lazyvillager._icon.classList.add('lazyvillager');
  markers.push(lazyvillager);
  var sanyu = L.marker([905.93, 338.66], {title: 'sanyu', icon: npcGenericIcon}).bindTooltip('Sanyu', {className: 'tooltip'}).addTo(map);
  sanyu._icon.classList.add('sanyu');
  markers.push(sanyu);
  var dembe = L.marker([910.93, 338.66], {title: 'dembe', icon: npcGenericIcon}).bindTooltip('Dembe', {className: 'tooltip'}).addTo(map);
  dembe._icon.classList.add('dembe');
  markers.push(dembe);
  var amateurcook = L.marker([915.93, 338.66], {title: 'amateurcook', icon: npcGenericIcon}).bindTooltip('Amateur Cook', {className: 'tooltip'}).addTo(map);
  amateurcook._icon.classList.add('amateurcook');
  markers.push(amateurcook);
  var politevillager = L.marker([925.07, 291.34], {title: 'politevillager', icon: npcGenericIcon}).bindTooltip('Polite Villager', {className: 'tooltip'}).addTo(map);
  politevillager._icon.classList.add('politevillager');
  markers.push(politevillager);
  var nonplussedvillager = L.marker([930.07, 291.34], {title: 'nonplussedvillager', icon: npcGenericIcon}).bindTooltip('Nonplussed Villager', {className: 'tooltip'}).addTo(map);
  nonplussedvillager._icon.classList.add('nonplussedvillager');
  markers.push(nonplussedvillager);
  var tofia = L.marker([937.47, 263.97], {title: 'tofia', icon: npcClothingIcon}).bindTooltip('Tofia', {className: 'tooltip'}).addTo(map);
  tofia._icon.classList.add('tofia');
  tofia._icon.classList.add('clothing');
  markers.push(tofia);
  var tofia = L.marker([937.47, 263.97], {title: 'tofia', icon: npcClothingIcon}).bindTooltip('Tofia', {className: 'tooltip'}).addTo(map);
  tofia._icon.classList.add('tofia');
  tofia._icon.classList.add('clothing');
  markers.push(tofia);
  var bigfootedshopper = L.marker([942.47, 263.97], {title: 'bigfootedshopper', icon: npcGenericIcon}).bindTooltip('Big-Footed Shopper', {className: 'tooltip'}).addTo(map);
  bigfootedshopper._icon.classList.add('bigfootedshopper');
  markers.push(bigfootedshopper);
  var myrislanman = L.marker([843.45, 264.22], {title: 'myrislanman', icon: npcGenericIcon}).bindTooltip('Myrislan Man', {className: 'tooltip'}).addTo(map);
  myrislanman._icon.classList.add('myrislanman');
  markers.push(myrislanman);
  var myrislanwoman = L.marker([854.71, 253.22], {title: 'myrislanwoman', icon: npcGenericIcon}).bindTooltip('Myrislan Woman', {className: 'tooltip'}).addTo(map);
  myrislanwoman._icon.classList.add('myrislanwoman');
  markers.push(myrislanwoman);
  var mokupunifruitcoop = L.marker([888.23, 271.97], {title: 'mokupunifruitcoop', icon: npcFruitIcon}).bindTooltip('Mokupuni Fruit Co-op', {className: 'tooltip'}).addTo(map);
  mokupunifruitcoop._icon.classList.add('mokupunifruitcoop');
  mokupunifruitcoop._icon.classList.add('fruit');
  markers.push(mokupunifruitcoop);
  var mokupunivendor = L.marker([889.23, 251.22], {title: 'mokupunivendor', icon: npcVendorIcon}).bindTooltip('Mokupuni Vendor', {className: 'tooltip'}).addTo(map);
  mokupunivendor._icon.classList.add('mokupunivendor');
  mokupunivendor._icon.classList.add('vendor');
  markers.push(mokupunivendor);
  var doria = L.marker([822.94, 244.21], {title: 'doria', icon: npcMovingIcon}).bindTooltip('Doria', {className: 'tooltip'}).addTo(map);
  doria._icon.classList.add('doria');
  doria._icon.classList.add('moving');
  markers.push(doria);
  var sisilia = L.marker([785.92, 268.72], {title: 'sisilia', icon: npcGenericIcon}).bindTooltip('Sisilia', {className: 'tooltip'}).addTo(map);
  sisilia._icon.classList.add('sisilia');
  markers.push(sisilia);
  var bingewatcher = L.marker([793.67, 289.97], {title: 'bingewatcher', icon: npcGenericIcon}).bindTooltip('Binge-Watcher', {className: 'tooltip'}).addTo(map);
  bingewatcher._icon.classList.add('bingewatcher');
  markers.push(bingewatcher);
  var mokupunivillager = L.marker([803.71, 222.77], {title: 'mokupunivillager', icon: npcGenericIcon}).bindTooltip('Mokupuni Villager', {className: 'tooltip'}).addTo(map);
  mokupunivillager._icon.classList.add('mokupunivillager');
  markers.push(mokupunivillager);
  var musicologist = L.marker([804.96, 219.4], {title: 'musicologist', icon: npcGenericIcon}).bindTooltip('Musicologist', {className: 'tooltip'}).addTo(map);
  musicologist._icon.classList.add('musicologist');
  markers.push(musicologist);
  var clumsyvillager = L.marker([834.42, 162.96], {title: 'clumsyvillager', icon: npcGenericIcon}).bindTooltip('Clumsy Villager', {className: 'tooltip'}).addTo(map);
  clumsyvillager._icon.classList.add('clumsyvillager');
  markers.push(clumsyvillager);
  var theelevatormistress = L.marker([853.18, 144.46], {title: 'theelevatormistress', icon: npcGenericIcon}).bindTooltip('The Elevator Mistress', {className: 'tooltip'}).addTo(map);
  theelevatormistress._icon.classList.add('theelevatormistress');
  markers.push(theelevatormistress);
  var tameronabreak = L.marker([928.49, 188.11], {title: 'tameronabreak', icon: npcGenericIcon}).bindTooltip('Tamer on a Break', {className: 'tooltip'}).addTo(map);
  tameronabreak._icon.classList.add('tameronabreak');
  markers.push(tameronabreak);
  var paea = L.marker([783.4, 179.39], {title: 'paea', icon: npcGenericIcon}).bindTooltip('Paea', {className: 'tooltip'}).addTo(map);
  paea._icon.classList.add('paea');
  markers.push(paea);
  var kalolina = L.marker([793.65, 144.25], {title: 'kalolina', icon: npcGenericIcon}).bindTooltip('Kalolina', {className: 'tooltip'}).addTo(map);
  kalolina._icon.classList.add('kalolina');
  markers.push(kalolina);
  var kelepi = L.marker([923.49, 183.11], {title: 'kelepi', icon: npcGenericIcon}).bindTooltip('Kelepi', {className: 'tooltip'}).addTo(map);
  kelepi._icon.classList.add('kelepi');
  markers.push(kelepi);
  var makerita = L.marker([928.49, 183.11], {title: 'makerita', icon: npcCombatIcon}).bindTooltip('Makerita', {className: 'tooltip'}).addTo(map);
  makerita._icon.classList.add('makerita');
  makerita._icon.classList.add('combat');
  markers.push(makerita);
  var sima = L.marker([933.49, 183.11], {title: 'sima', icon: npcCombatIcon}).bindTooltip('Sima', {className: 'tooltip'}).addTo(map);
  sima._icon.classList.add('sima');
  sima._icon.classList.add('combat');
  markers.push(sima);
  var kehaulani = L.marker([930.49, 188.11], {title: 'kehaulani', icon: npcCombatIcon}).bindTooltip('Kehaulani', {className: 'tooltip'}).addTo(map);
  kehaulani._icon.classList.add('kehaulani');
  kehaulani._icon.classList.add('combat');
  markers.push(kehaulani);
  var teulia = L.marker([925.49, 188.11], {title: 'teulia', icon: npcCombatIcon}).bindTooltip('Teulia', {className: 'tooltip'}).addTo(map);
  teulia._icon.classList.add('teulia');
  teulia._icon.classList.add('combat');
  markers.push(teulia);
  var rawiri = L.marker([928.49, 193.11], {title: 'rawiri', icon: npcRawiriIcon}).bindTooltip('Rawiri', {className: 'tooltip'}).addTo(map);
  rawiri._icon.classList.add('rawiri');
  rawiri._icon.classList.add('combat');
  markers.push(rawiri);
  var kauri = L.marker([576.03, 589.14], {title: 'kauri', icon: npcGenericIcon}).bindTooltip('Kauri', {className: 'tooltip'}).addTo(map);
  kauri._icon.classList.add('kauri');
  markers.push(kauri);
  var salasmasina = L.marker([587.8, 585.51], {title: 'salasmasina', icon: npcGenericIcon}).bindTooltip('Salasmasina', {className: 'tooltip'}).addTo(map);
  salasmasina._icon.classList.add('salasmasina');
  markers.push(salasmasina);
  var diloa = L.marker([598.3, 532.25], {title: 'diloa', icon: npcCombatIcon}).bindTooltip('Diloa', {className: 'tooltip'}).addTo(map);
  diloa._icon.classList.add('diloa');
  diloa._icon.classList.add('combat');
  markers.push(diloa);
  var kaione = L.marker([587.35, 495.8], {title: 'kaione', icon: npcCombatIcon}).bindTooltip('Kaione', {className: 'tooltip'}).addTo(map);
  kaione._icon.classList.add('kaione');
  kaione._icon.classList.add('combat');
  markers.push(kaione);
  var shimpar = L.marker([512.46, 498.1], {title: 'shimpar', icon: npcCombatIcon}).bindTooltip('Shimpar', {className: 'tooltip'}).addTo(map);
  shimpar._icon.classList.add('shimpar');
  shimpar._icon.classList.add('combat');
  markers.push(shimpar);
  var lau = L.marker([517.46, 494.6], {title: 'lau', icon: npcCombatIcon}).bindTooltip('Lau', {className: 'tooltip'}).addTo(map);
  lau._icon.classList.add('lau');
  lau._icon.classList.add('combat');
  markers.push(lau);
  var iaheto = L.marker([530.47, 441.09], {title: 'iaheto', icon: npcCombatIcon}).bindTooltip('Iaheto', {className: 'tooltip'}).addTo(map);
  iaheto._icon.classList.add('iaheto');
  iaheto._icon.classList.add('combat');
  markers.push(iaheto);
  var timena = L.marker([526.71, 441.09], {title: 'timena', icon: npcCombatIcon}).bindTooltip('Timena', {className: 'tooltip'}).addTo(map);
  timena._icon.classList.add('timena');
  timena._icon.classList.add('combat');
  markers.push(timena);
  var vealakepa = L.marker([597.5, 438.09], {title: 'vealakepa', icon: npcCombatIcon}).bindTooltip('Vealakepa', {className: 'tooltip'}).addTo(map);
  vealakepa._icon.classList.add('vealakepa');
  vealakepa._icon.classList.add('combat');
  markers.push(vealakepa);
  var ulia = L.marker([598, 438.09], {title: 'ulia', icon: npcCombatIcon}).bindTooltip('Ulia', {className: 'tooltip'}).addTo(map);
  ulia._icon.classList.add('ulia');
  ulia._icon.classList.add('combat');
  markers.push(ulia);
  var pisila = L.marker([594.8, 399.48], {title: 'pisila', icon: npcCombatIcon}).bindTooltip('Pisila', {className: 'tooltip'}).addTo(map);
  pisila._icon.classList.add('pisila');
  pisila._icon.classList.add('combat');
  markers.push(pisila);
  var asupa = L.marker([599.03, 402.74], {title: 'asupa', icon: npcCombatIcon}).bindTooltip('Asupa', {className: 'tooltip'}).addTo(map);
  asupa._icon.classList.add('asupa');
  asupa._icon.classList.add('combat');
  markers.push(asupa);
  var pua = L.marker([562.26, 429.37], {title: 'pua', icon: npcCombatIcon}).bindTooltip('Pua', {className: 'tooltip'}).addTo(map);
  pua._icon.classList.add('pua');
  pua._icon.classList.add('combat');
  markers.push(pua);
  var visesia = L.marker([648.36, 377.23], {title: 'visesia', icon: npcGenericIcon}).bindTooltip('Visesia', {className: 'tooltip'}).addTo(map);
  visesia._icon.classList.add('visesia');
  markers.push(visesia);
  var visesiasagent = L.marker([651.36, 377.23], {title: 'visesiasagent', icon: npcGenericIcon}).bindTooltip("Visesia's Agent", {className: 'tooltip'}).addTo(map);
  visesiasagent._icon.classList.add('visesiasagent');
  markers.push(visesiasagent);
  var cameraman = L.marker([649.36, 472.65], {title: 'cameraman', icon: npcGenericIcon}).bindTooltip('Cameraman', {className: 'tooltip'}).addTo(map);
  cameraman._icon.classList.add('cameraman');
  markers.push(cameraman);
  var screenwriter = L.marker([649.36, 475.65], {title: 'screenwriter', icon: npcGenericIcon}).bindTooltip('Screenwriter', {className: 'tooltip'}).addTo(map);
  screenwriter._icon.classList.add('screenwriter');
  markers.push(screenwriter);
  var akanesi = L.marker([621.97, 495.53], {title: 'akanesi', icon: npcCombatIcon}).bindTooltip('Akanesi', {className: 'tooltip'}).addTo(map);
  akanesi._icon.classList.add('akanesi');
  akanesi._icon.classList.add('combat');
  markers.push(akanesi);
  var waryfruitpicker = L.marker([509.69, 362.23], {title: 'waryfruitpicker', icon: npcCombatIcon}).bindTooltip('Wary Fruit Picker', {className: 'tooltip'}).addTo(map);
  waryfruitpicker._icon.classList.add('waryfruitpicker');
  waryfruitpicker._icon.classList.add('combat');
  markers.push(waryfruitpicker);
  var chillfruitpicker = L.marker([509.69, 350.73], {title: 'chillfruitpicker', icon: npcCombatIcon}).bindTooltip('Chill Fruit Picker', {className: 'tooltip'}).addTo(map);
  chillfruitpicker._icon.classList.add('chillfruitpicker');
  chillfruitpicker._icon.classList.add('combat');
  markers.push(chillfruitpicker);
  var namono = L.marker([568.23, 302], {title: 'namono', icon: npcGenericIcon}).bindTooltip('Namono', {className: 'tooltip'}).addTo(map);
  namono._icon.classList.add('namono');
  markers.push(namono);
  var banyangardener = L.marker([512.88, 159.77], {title: 'banyangardener', icon: npcGenericIcon}).bindTooltip('Banyan Gardener', {className: 'tooltip'}).addTo(map);
  banyangardener._icon.classList.add('banyangardener');
  markers.push(banyangardener);
  var sefita = L.marker([534.63, 170.4], {title: 'sefita', icon: npcGenericIcon}).bindTooltip('Sefita', {className: 'tooltip'}).addTo(map);
  sefita._icon.classList.add('sefita');
  markers.push(sefita);
  var tani = L.marker([625.06, 149.16], {title: 'tani', icon: npcGenericIcon}).bindTooltip('Tani', {className: 'tooltip'}).addTo(map);
  tani._icon.classList.add('tani');
  markers.push(tani);
  var omninesianreporter = L.marker([632.16, 198.17], {title: 'omninesianreporter', icon: npcGenericIcon}).bindTooltip('Omninesian Reporter', {className: 'tooltip'}).addTo(map);
  omninesianreporter._icon.classList.add('omninesianreporter');
  markers.push(omninesianreporter);
  var dojoenforcer = L.marker([357.99, 604.47], {title: 'dojoenforcer', icon: npcGenericIcon}).bindTooltip('Dojo Enforcer', {className: 'tooltip'}).addTo(map);
  dojoenforcer._icon.classList.add('dojoenforcer');
  markers.push(dojoenforcer);
  var lonelyvendor = L.marker([414.49, 586.97], {title: 'lonelyvendor', icon: npcVendorIcon}).bindTooltip('Lonely Vendor', {className: 'tooltip'}).addTo(map);
  lonelyvendor._icon.classList.add('lonelyvendor');
  lonelyvendor._icon.classList.add('vendor');
  markers.push(lonelyvendor);
  var pasinita = L.marker([369.74, 580.84], {title: 'pasinita', icon: npcGenericIcon}).bindTooltip('Pasinita', {className: 'tooltip'}).addTo(map);
  pasinita._icon.classList.add('pasinita');
  markers.push(pasinita);
  var susi = L.marker([372.36, 579.21], {title: 'susi', icon: npcGenericIcon}).bindTooltip('Susi', {className: 'tooltip'}).addTo(map);
  susi._icon.classList.add('susi');
  markers.push(susi);
  var soni = L.marker([383.24, 557.33], {title: 'soni', icon: npcCombatIcon}).bindTooltip('Soni', {className: 'tooltip'}).addTo(map);
  soni._icon.classList.add('soni');
  soni._icon.classList.add('combat');
  markers.push(soni);
  var mau = L.marker([368.99, 526.58], {title: 'mau', icon: npcCombatIcon}).bindTooltip('Mau', {className: 'tooltip'}).addTo(map);
  mau._icon.classList.add('mau');
  mau._icon.classList.add('combat');
  markers.push(mau);
  var tuifua = L.marker([497.45, 483.72], {title: 'tuifua', icon: npcCombatIcon}).bindTooltip('Tuifua', {className: 'tooltip'}).addTo(map);
  tuifua._icon.classList.add('tuifua');
  tuifua._icon.classList.add('combat');
  markers.push(tuifua);
  var fololini = L.marker([387.2, 470.35], {title: 'fololini', icon: npcCombatIcon}).bindTooltip('Fololini', {className: 'tooltip'}).addTo(map);
  fololini._icon.classList.add('fololini');
  fololini._icon.classList.add('combat');
  markers.push(fololini);
  var pelenatita = L.marker([397.7, 489.6], {title: 'pelenatita', icon: npcCombatIcon}).bindTooltip('Pelenatita', {className: 'tooltip'}).addTo(map);
  pelenatita._icon.classList.add('pelenatita');
  pelenatita._icon.classList.add('combat');
  markers.push(pelenatita);
  var akechi = L.marker([401.43, 437.61], {title: 'akechi', icon: npcCombatIcon}).bindTooltip('Akechi', {className: 'tooltip'}).addTo(map);
  akechi._icon.classList.add('akechi');
  akechi._icon.classList.add('combat');
  markers.push(akechi);
  var lesieli = L.marker([305.7, 429.52], {title: 'lesieli', icon: npcCombatIcon}).bindTooltip('Lesieli', {className: 'tooltip'}).addTo(map);
  lesieli._icon.classList.add('lesieli');
  lesieli._icon.classList.add('combat');
  markers.push(lesieli);
  var makisi = L.marker([305.32, 449.03], {title: 'makisi', icon: npcCombatIcon}).bindTooltip('Makisi', {className: 'tooltip'}).addTo(map);
  makisi._icon.classList.add('makisi');
  makisi._icon.classList.add('combat');
  markers.push(makisi);
  var alefosio = L.marker([387.38, 337.12], {title: 'alefosio', icon: npcMovingCombatIcon}).bindTooltip('Alefosio', {className: 'tooltip'}).addTo(map);
  alefosio._icon.classList.add('alefosio');
  alefosio._icon.classList.add('moving');
  alefosio._icon.classList.add('combat');
  markers.push(alefosio);
  var eleona = L.marker([397.5, 238.65], {title: 'eleona', icon: npcCombatIcon}).bindTooltip('Eleona', {className: 'tooltip'}).addTo(map);
  eleona._icon.classList.add('eleona');
  eleona._icon.classList.add('combat');
  markers.push(eleona);
  var volcanologist = L.marker([218.49, 225.02], {title: 'volcanologist', icon: npcGenericIcon}).bindTooltip('Volcanologist', {className: 'tooltip'}).addTo(map);
  volcanologist._icon.classList.add('volcanologist');
  markers.push(volcanologist);
  var crystalminer = L.marker([131.13, 231.61], {title: 'crystalminer', icon: npcGenericIcon}).bindTooltip('Crystal Miner', {className: 'tooltip'}).addTo(map);
  crystalminer._icon.classList.add('crystalminer');
  markers.push(crystalminer);
  var concernedvendor = L.marker([116.12, 301.14], {title: 'concernedvendor', icon: npcVendorIcon}).bindTooltip('Concerned Vendor', {className: 'tooltip'}).addTo(map);
  concernedvendor._icon.classList.add('concernedvendor');
  concernedvendor._icon.classList.add('vendor');
  markers.push(concernedvendor);
  var carelesssightseer = L.marker([89.49, 294.14], {title: 'carelesssightseer', icon: npcGenericIcon}).bindTooltip('Careless Sightseer', {className: 'tooltip'}).addTo(map);
  carelesssightseer._icon.classList.add('carelesssightseer');
  markers.push(carelesssightseer);
  var evalon = L.marker([108.29, 538.66], {title: 'evalon', icon: npcCombatIcon}).bindTooltip('Evalon', {className: 'tooltip'}).addTo(map);
  evalon._icon.classList.add('evalon');
  evalon._icon.classList.add('combat');
  markers.push(evalon);
  var ngaoa = L.marker([97.92, 523.16], {title: 'ngaoa', icon: npcCombatIcon}).bindTooltip('Ngaoa', {className: 'tooltip'}).addTo(map);
  ngaoa._icon.classList.add('ngaoa');
  ngaoa._icon.classList.add('combat');
  markers.push(ngaoa);
  var eni = L.marker([188.36, 523.26], {title: 'eni', icon: npcCombatIcon}).bindTooltip('Eni', {className: 'tooltip'}).addTo(map);
  eni._icon.classList.add('eni');
  eni._icon.classList.add('combat');
  markers.push(eni);
  var miremba = L.marker([174.86, 523.51], {title: 'miremba', icon: npcCombatIcon}).bindTooltip('Miremba', {className: 'tooltip'}).addTo(map);
  miremba._icon.classList.add('miremba');
  miremba._icon.classList.add('combat');
  markers.push(miremba);
  var malia = L.marker([240.5, 469.86], {title: 'malia', icon: npcMovingIcon}).bindTooltip('Malia', {className: 'tooltip'}).addTo(map);
  malia._icon.classList.add('malia');
  malia._icon.classList.add('moving');
  markers.push(malia);
  var sesika = L.marker([268.65, 522.09], {title: 'sesika', icon: npcCombatIcon}).bindTooltip('Sesika', {className: 'tooltip'}).addTo(map);
  sesika._icon.classList.add('sesika');
  sesika._icon.classList.add('combat');
  markers.push(sesika);
  var toakase = L.marker([265.65, 521.84], {title: 'toakase', icon: npcCombatIcon}).bindTooltip('Toakase', {className: 'tooltip'}).addTo(map);
  toakase._icon.classList.add('toakase');
  toakase._icon.classList.add('combat');
  markers.push(toakase);
  var maunga = L.marker([259.31, 561.89], {title: 'maunga', icon: npcCombatIcon}).bindTooltip('Maunga', {className: 'tooltip'}).addTo(map);
  maunga._icon.classList.add('maunga');
  maunga._icon.classList.add('combat');
  markers.push(maunga);
  var teroera = L.marker([254.44, 540.13], {title: 'teroera', icon: npcCombatIcon}).bindTooltip('Te Roera', {className: 'tooltip'}).addTo(map);
  teroera._icon.classList.add('teroera');
  teroera._icon.classList.add('combat');
  markers.push(teroera);
  var claire = L.marker([219.06, 537.38], {title: 'claire', icon: npcCombatIcon}).bindTooltip('Claire', {className: 'tooltip'}).addTo(map);
  claire._icon.classList.add('claire');
  claire._icon.classList.add('combat');
  markers.push(claire);
  var meleseini = L.marker([301.64, 575.61], {title: 'meleseini', icon: npcGenericIcon}).bindTooltip('Meleseini', {className: 'tooltip'}).addTo(map);
  meleseini._icon.classList.add('meleseini');
  markers.push(meleseini);
  var belsotowatchwoman = L.marker([176.24, 400.42], {title: 'belsotowatchwoman', icon: npcCombatIcon}).bindTooltip('Belsoto Watchwoman', {className: 'tooltip'}).addTo(map);
  belsotowatchwoman._icon.classList.add('belsotowatchwoman');
  belsotowatchwoman._icon.classList.add('combat');
  markers.push(belsotowatchwoman);
  var belsotowatchman = L.marker([169.24, 392.67], {title: 'belsotowatchman', icon: npcCombatIcon}).bindTooltip('Belsoto Watchman', {className: 'tooltip'}).addTo(map);
  belsotowatchman._icon.classList.add('belsotowatchman');
  belsotowatchman._icon.classList.add('combat');
  markers.push(belsotowatchman);
  var lila = L.marker([96.62, 423.05], {title: 'lila', icon: npcCombatIcon}).bindTooltip('Lila', {className: 'tooltip'}).addTo(map);
  lila._icon.classList.add('lila');
  lila._icon.classList.add('combat');
  markers.push(lila);
  var etu = L.marker([83.25, 412.17], {title: 'etu', icon: npcCombatIcon}).bindTooltip('Etu', {className: 'tooltip'}).addTo(map);
  etu._icon.classList.add('etu');
  etu._icon.classList.add('combat');
  markers.push(etu);
  var kaniela = L.marker([67.37, 431.05], {title: 'kaniela', icon: npcCombatIcon}).bindTooltip('Kaniela', {className: 'tooltip'}).addTo(map);
  kaniela._icon.classList.add('kaniela');
  kaniela._icon.classList.add('combat');
  markers.push(kaniela);
  var crystalinvestor = L.marker([124.38, 454.24], {title: 'crystalinvestor', icon: npcGenericIcon}).bindTooltip('Crystal Investor', {className: 'tooltip'}).addTo(map);
  crystalinvestor._icon.classList.add('crystalinvestor');
  markers.push(crystalinvestor);
  var belsotowatchman = L.marker([158.96, 718.68], {title: 'belsotowatchman', icon: npcMovingIcon}).bindTooltip('Belsoto Watchman', {className: 'tooltip'}).addTo(map);
  belsotowatchman._icon.classList.add('belsotowatchman');
  belsotowatchman._icon.classList.add('moving');
  markers.push(belsotowatchman);
  var localsupplier = L.marker([196.88, 761.9], {title: 'localsupplier', icon: npcGenericIcon}).bindTooltip('Local Supplier', {className: 'tooltip'}).addTo(map);
  localsupplier._icon.classList.add('localsupplier');
  markers.push(localsupplier);
  var belsotosympathizer = L.marker([201.86, 698.41], {title: 'belsotosympathizer', icon: npcCombatIcon}).bindTooltip('Belsoto Sympathizer', {className: 'tooltip'}).addTo(map);
  belsotosympathizer._icon.classList.add('belsotosympathizer');
  belsotosympathizer._icon.classList.add('combat');
  markers.push(belsotosympathizer);
  var vili = L.marker([272.85, 672.28], {title: 'vili', icon: npcCombatIcon}).bindTooltip('Vili', {className: 'tooltip'}).addTo(map);
  vili._icon.classList.add('vili');
  vili._icon.classList.add('combat');
  markers.push(vili);
  var sipiliano = L.marker([290.6, 692.54], {title: 'sipiliano', icon: npcCombatIcon}).bindTooltip('Sipiliano', {className: 'tooltip'}).addTo(map);
  sipiliano._icon.classList.add('sipiliano');
  sipiliano._icon.classList.add('combat');
  markers.push(sipiliano);
  var rahnee = L.marker([357.48, 819.73], {title: 'rahnee', icon: npcCombatIcon}).bindTooltip('Rahnee', {className: 'tooltip'}).addTo(map);
  rahnee._icon.classList.add('rahnee');
  rahnee._icon.classList.add('combat');
  markers.push(rahnee);
  var jono = L.marker([353.23, 811.48], {title: 'jono', icon: npcCombatIcon}).bindTooltip('Jono', {className: 'tooltip'}).addTo(map);
  jono._icon.classList.add('jono');
  jono._icon.classList.add('combat');
  markers.push(jono);
  var alosina = L.marker([348.48, 821.48], {title: 'alosina', icon: npcCombatIcon}).bindTooltip('Alosina', {className: 'tooltip'}).addTo(map);
  alosina._icon.classList.add('alosina');
  alosina._icon.classList.add('combat');
  markers.push(alosina);
  var pare = L.marker([367.6, 839.36], {title: 'pare', icon: npcCombatIcon}).bindTooltip('Pare', {className: 'tooltip'}).addTo(map);
  pare._icon.classList.add('pare');
  pare._icon.classList.add('combat');
  markers.push(pare);
  var meretini = L.marker([367.6, 841.73], {title: 'meretini', icon: npcCombatIcon}).bindTooltip('Meretini', {className: 'tooltip'}).addTo(map);
  meretini._icon.classList.add('meretini');
  meretini._icon.classList.add('combat');
  markers.push(meretini);
  var lavinia = L.marker([393.64, 915.65], {title: 'lavinia', icon: npcCombatIcon}).bindTooltip('Lavinia', {className: 'tooltip'}).addTo(map);
  lavinia._icon.classList.add('lavinia');
  lavinia._icon.classList.add('combat');
  markers.push(lavinia);
  var taaga = L.marker([393.64, 918.78], {title: 'taaga', icon: npcCombatIcon}).bindTooltip('Taaga', {className: 'tooltip'}).addTo(map);
  taaga._icon.classList.add('taaga');
  taaga._icon.classList.add('combat');
  markers.push(taaga);
  var peau = L.marker([385.77, 903.03], {title: 'peau', icon: npcCombatIcon}).bindTooltip('Peau', {className: 'tooltip'}).addTo(map);
  peau._icon.classList.add('peau');
  peau._icon.classList.add('combat');
  markers.push(peau);
  var belsotofanatic = L.marker([290.15, 798.66], {title: 'belsotofanatic', icon: npcCombatIcon}).bindTooltip('Belsoto Fanatic', {className: 'tooltip'}).addTo(map);
  belsotofanatic._icon.classList.add('belsotofanatic');
  belsotofanatic._icon.classList.add('combat');
  markers.push(belsotofanatic);
  var daredevil = L.marker([261.76, 739.49], {title: 'daredevil', icon: npcGenericIcon}).bindTooltip('Daredevil', {className: 'tooltip'}).addTo(map);
  daredevil._icon.classList.add('daredevil');
  markers.push(daredevil);
  var salote = L.marker([325.27, 707.75], {title: 'salote', icon: npcCombatIcon}).bindTooltip('Salote', {className: 'tooltip'}).addTo(map);
  salote._icon.classList.add('salote');
  salote._icon.classList.add('combat');
  markers.push(salote);
  var fololesia = L.marker([314.52, 722.63], {title: 'fololesia', icon: npcCombatIcon}).bindTooltip('Fololesia', {className: 'tooltip'}).addTo(map);
  fololesia._icon.classList.add('fololesia');
  fololesia._icon.classList.add('combat');
  markers.push(fololesia);
  var anaknovice = L.marker([349.13, 711.12], {title: 'anaknovice', icon: npcFireGuardIcon}).bindTooltip('Anak Novice', {className: 'tooltip'}).addTo(map);
  anaknovice._icon.classList.add('anaknovice');
  anaknovice._icon.classList.add('combat');
  markers.push(anaknovice);
  var anakinitiate = L.marker([356.26, 694.74], {title: 'anakinitiate', icon: npcFireGuardIcon}).bindTooltip('Anak Initiate', {className: 'tooltip'}).addTo(map);
  anakinitiate._icon.classList.add('anakinitiate');
  anakinitiate._icon.classList.add('combat');
  markers.push(anakinitiate);
  var anakdisciple = L.marker([363.26, 711], {title: 'anakdisciple', icon: npcFireGuardIcon}).bindTooltip('Anak Disciple', {className: 'tooltip'}).addTo(map);
  anakdisciple._icon.classList.add('anakdisciple');
  anakdisciple._icon.classList.add('combat');
  markers.push(anakdisciple);
  var anakpriest = L.marker([371.51, 702.74], {title: 'anakpriest', icon: npcFireGuardIcon}).bindTooltip('Anak Priest', {className: 'tooltip'}).addTo(map);
  anakpriest._icon.classList.add('anakpriest');
  anakpriest._icon.classList.add('combat');
  markers.push(anakpriest);
  var labassistant = L.marker([151.81, 811.33], {title: 'labassistant', icon: npcCombatIcon}).bindTooltip('Lab Assistant', {className: 'tooltip'}).addTo(map);
  labassistant._icon.classList.add('labassistant');
  labassistant._icon.classList.add('combat');
  markers.push(labassistant);
  var labassistant = L.marker([162.93, 832.95], {title: 'labassistant', icon: npcCombatIcon}).bindTooltip('Lab Assistant', {className: 'tooltip'}).addTo(map);
  labassistant._icon.classList.add('labassistant');
  labassistant._icon.classList.add('combat');
  markers.push(labassistant);
  var leka = L.marker([336.96, 738.28], {title: 'leka', icon: npcCombatIcon}).bindTooltip('Leka', {className: 'tooltip'}).addTo(map);
  leka._icon.classList.add('leka');
  leka._icon.classList.add('combat');
  markers.push(leka);
  
  // Use the tool over at https://codepen.io/susanpallmann/full/eYzbOyJ to format entries easier!
  
  //var name = L.marker([00, 00], {title: name, icon: npcGenericIcon}).bindTooltip("name", {className: 'tooltip'}).addTo(map);
  //name._icon.classList.add("testclass");
  //markers.push(name);
  
  function listSearchResults(query) {
    $('#results').empty();
    var counter = 0; 
    for (var i in markers){
      if (counter <= 4) {
        var markerID = markers[i].options.title;
        var markerToolTip = markers[i].getTooltip();
        var content = markerToolTip.getContent();
        var source = markers[i].options.icon.options.iconUrl;
        if (markerID.includes(query)){
          counter += 1;
          $('#results').append('<li><a href="" class="result-link" id="' + markerID + '"><img class="marker-small" src="' + source + '" alt="" /><p>' + content + '</p></a></li>');
        }
      }
    }
  }
  
  function refreshSearch(query) {
    $('.leaflet-marker-icon').addClass('hidden-icon');
    $('*[class*=' + query + ']').removeClass('hidden-icon');
  }
  
  $("#search").bind('input', function(){
    let value = $("#search").val();
    value = value.replace(/[^a-z0-9\s]/gi, '').replace(/[_\s]/g, '').toLowerCase();
    if (value === '') {
      $('.leaflet-marker-icon').removeClass('hidden-icon');
      $('#results').empty();
    } else {
      refreshSearch(value);
      listSearchResults(value);
    }
  });
  
  $('input[type="checkbox"]').bind('input', function(){
    $('.leaflet-marker-icon').addClass('hidden-icon');
    if ($('input:checkbox:checked').length) {
      $('input:checkbox:checked').each(function(index) {
        let key = $(this).val();
        console.log(key);
        $('.' + key).removeClass('hidden-icon');
      });
    } else {
      $('.leaflet-marker-icon').removeClass('hidden-icon');
    }
  });
});

$(document).on('click','.result-link',function(e){
  function markerFunction(id){
    for (var i in markers){
      var markerID = markers[i].options.title;
      if (markerID === id){
        markers[i].openTooltip();
        map.panTo(markers[i].getLatLng());
      } else {
        markers[i].closeTooltip();
      }
    }
  }
  markerFunction($(this).attr('id'));
  e.preventDefault();
}); 
