var markers = [];
var map;

$(document).ready(function() {  
  
    map = L.map('map-tucma', {
        crs: L.CRS.Simple,
        attributionControl: false,
        minZoom: 1,
        preferCanvas: true
    });
  
  var bounds = [[0,0], [1000,1000]];
  var image = L.imageOverlay('images/maps/tucma.png', bounds).addTo(map);
  map.fitBounds(bounds);
  
  L.control.mousePosition().addTo(map);

  var TemMarker = L.Icon.extend({
    options: {
        shadowUrl: '',
        iconSize:     [39, 51], // size of the icon
        shadowSize:   [0, 0], // size of the shadow
        iconAnchor:   [22, 51], // point of the icon which will correspond to marker's location
        shadowAnchor: [0, 0],  // the same for the shadow
        popupAnchor:  [19, 0], // point from which the popup should open relative to the iconAnchor
        tooltipAnchor: [24, -30]
    }
  });
  var npcGenericIcon = new TemMarker({iconUrl: 'images/icons/npc.png'});
  var npcMovingIcon = new TemMarker({iconUrl: 'images/icons/npc-moving.png'});
  var npcVendorIcon = new TemMarker({iconUrl: 'images/icons/npc-vendor.png'});
  var npcClothingIcon = new TemMarker({iconUrl: 'images/icons/npc-clothing.png'});
  var npcFurnitureIcon = new TemMarker({iconUrl: 'images/icons/npc-furniture.png'});
  var npcCombatIcon = new TemMarker({iconUrl: 'images/icons/npc-combat.png'});
  var npcMovingCombatIcon = new TemMarker({iconUrl: 'images/icons/npc-moving-combat.png'});
  var npcProfessorKonstantinosIcon = new TemMarker({iconUrl: 'images/icons/professor-konstantinos.png'});
  var npcAdiaTurayIcon = new TemMarker({iconUrl: 'images/icons/adia-turay.png'}); 
  var npcYareniIcon = new TemMarker({iconUrl: 'images/icons/yareni.png'});  
  var npcCrystalGuardIcon = new TemMarker({iconUrl: 'images/icons/npc-crystal-guard.png'});
  
  var agustn = L.marker([826.95, 542.88], {title: 'agustn', icon: npcGenericIcon}).bindTooltip('Agustín', {className: 'tooltip'}).addTo(map);
  agustn._icon.classList.add('agustn');
  markers.push(agustn);
  var walter = L.marker([827.22, 519.85], {title: 'walter', icon: npcGenericIcon}).bindTooltip('Walter', {className: 'tooltip'}).addTo(map);
  walter._icon.classList.add('walter');
  markers.push(walter);
  var frustratedtaveler = L.marker([806.47, 545.36], {title: 'frustratedtaveler', icon: npcGenericIcon}).bindTooltip('Frustrated Taveler', {className: 'tooltip'}).addTo(map);
  frustratedtaveler._icon.classList.add('frustratedtaveler');
  markers.push(frustratedtaveler);
  var ameyali = L.marker([796.1, 510.48], {title: 'ameyali', icon: npcGenericIcon}).bindTooltip('Ameyali', {className: 'tooltip'}).addTo(map);
  ameyali._icon.classList.add('ameyali');
  markers.push(ameyali);
  var airshipterminalguard = L.marker([762.56, 527.54], {title: 'airshipterminalguard', icon: npcGenericIcon}).bindTooltip('Airship Terminal Guard', {className: 'tooltip'}).addTo(map);
  airshipterminalguard._icon.classList.add('airshipterminalguard');
  markers.push(airshipterminalguard);
  var waitingtraveler = L.marker([760.81, 561.55], {title: 'waitingtraveler', icon: npcGenericIcon}).bindTooltip('Waiting Traveler', {className: 'tooltip'}).addTo(map);
  waitingtraveler._icon.classList.add('waitingtraveler');
  markers.push(waitingtraveler);
  var temtemconnoisseur = L.marker([760.81, 564.55], {title: 'temtemconnoisseur', icon: npcGenericIcon}).bindTooltip('Temtem Connoisseur', {className: 'tooltip'}).addTo(map);
  temtemconnoisseur._icon.classList.add('temtemconnoisseur');
  markers.push(temtemconnoisseur);
  var quetzaliantravelagent = L.marker([760.81, 567.55], {title: 'quetzaliantravelagent', icon: npcGenericIcon}).bindTooltip('Quetzalian Travel Agent', {className: 'tooltip'}).addTo(map);
  quetzaliantravelagent._icon.classList.add('quetzaliantravelagent');
  markers.push(quetzaliantravelagent);
  var tucmatouristguide = L.marker([760.81, 570.55], {title: 'tucmatouristguide', icon: npcGenericIcon}).bindTooltip('Tucma Tourist Guide', {className: 'tooltip'}).addTo(map);
  tucmatouristguide._icon.classList.add('tucmatouristguide');
  markers.push(tucmatouristguide);
  var drunkminer = L.marker([761.82, 462.67], {title: 'drunkminer', icon: npcGenericIcon}).bindTooltip('Drunk Miner', {className: 'tooltip'}).addTo(map);
  drunkminer._icon.classList.add('drunkminer');
  markers.push(drunkminer);
  var cocijo = L.marker([761.82, 465.67], {title: 'cocijo', icon: npcGenericIcon}).bindTooltip('Cocijo', {className: 'tooltip'}).addTo(map);
  cocijo._icon.classList.add('cocijo');
  markers.push(cocijo);
  var drunktamer = L.marker([761.82, 468.67], {title: 'drunktamer', icon: npcGenericIcon}).bindTooltip('Drunk Tamer', {className: 'tooltip'}).addTo(map);
  drunktamer._icon.classList.add('drunktamer');
  markers.push(drunktamer);
  var kuikal = L.marker([761.82, 471.67], {title: 'kuikal', icon: npcGenericIcon}).bindTooltip('Kuikal', {className: 'tooltip'}).addTo(map);
  kuikal._icon.classList.add('kuikal');
  markers.push(kuikal);
  var merryquetzalian = L.marker([761.82, 474.67], {title: 'merryquetzalian', icon: npcGenericIcon}).bindTooltip('Merry Quetzalian', {className: 'tooltip'}).addTo(map);
  merryquetzalian._icon.classList.add('merryquetzalian');
  markers.push(merryquetzalian);
  var xipetotec = L.marker([761.82, 477.67], {title: 'xipetotec', icon: npcGenericIcon}).bindTooltip('Xipe Totec', {className: 'tooltip'}).addTo(map);
  xipetotec._icon.classList.add('xipetotec');
  markers.push(xipetotec);
  var yela = L.marker([765.82, 462.67], {title: 'yela', icon: npcGenericIcon}).bindTooltip('Yela', {className: 'tooltip'}).addTo(map);
  yela._icon.classList.add('yela');
  markers.push(yela);
  var kitchenhand = L.marker([765.82, 465.67], {title: 'kitchenhand', icon: npcGenericIcon}).bindTooltip('Kitchen Hand', {className: 'tooltip'}).addTo(map);
  kitchenhand._icon.classList.add('kitchenhand');
  markers.push(kitchenhand);
  var travelingmerchant = L.marker([765.82, 468.67], {title: 'travelingmerchant', icon: npcGenericIcon}).bindTooltip('Traveling Merchant', {className: 'tooltip'}).addTo(map);
  travelingmerchant._icon.classList.add('travelingmerchant');
  markers.push(travelingmerchant);
  var jimena = L.marker([765.82, 471.67], {title: 'jimena', icon: npcGenericIcon}).bindTooltip('Jimena', {className: 'tooltip'}).addTo(map);
  jimena._icon.classList.add('jimena');
  markers.push(jimena);
  var iztli = L.marker([765.82, 474.67], {title: 'iztli', icon: npcGenericIcon}).bindTooltip('Iztli', {className: 'tooltip'}).addTo(map);
  iztli._icon.classList.add('iztli');
  markers.push(iztli);
  var unreachablekitchenhand = L.marker([765.82, 477.67], {title: 'unreachablekitchenhand', icon: npcMovingIcon}).bindTooltip('Unreachable Kitchen Hand', {className: 'tooltip'}).addTo(map);
  unreachablekitchenhand._icon.classList.add('unreachablekitchenhand');
  unreachablekitchenhand._icon.classList.add('moving');
  markers.push(unreachablekitchenhand);
  var drunksmith = L.marker([765.82, 480.67], {title: 'drunksmith', icon: npcGenericIcon}).bindTooltip('Drunk Smith', {className: 'tooltip'}).addTo(map);
  drunksmith._icon.classList.add('drunksmith');
  markers.push(drunksmith);
  var akatzin = L.marker([762.08, 449.83], {title: 'akatzin', icon: npcGenericIcon}).bindTooltip('Akatzin', {className: 'tooltip'}).addTo(map);
  akatzin._icon.classList.add('akatzin');
  markers.push(akatzin);
  var yeyetzi = L.marker([764.9, 424.07], {title: 'yeyetzi', icon: npcGenericIcon}).bindTooltip('Yeyetzi', {className: 'tooltip'}).addTo(map);
  yeyetzi._icon.classList.add('yeyetzi');
  markers.push(yeyetzi);
  var koyolli = L.marker([763.14, 424.07], {title: 'koyolli', icon: npcGenericIcon}).bindTooltip('Koyolli', {className: 'tooltip'}).addTo(map);
  koyolli._icon.classList.add('koyolli');
  markers.push(koyolli);
  var quetzaliancitizen = L.marker([806.4, 434.83], {title: 'quetzaliancitizen', icon: npcGenericIcon}).bindTooltip('Quetzalian Citizen', {className: 'tooltip'}).addTo(map);
  quetzaliancitizen._icon.classList.add('quetzaliancitizen');
  markers.push(quetzaliancitizen);
  var defeatedtamer = L.marker([824.02, 418.21], {title: 'defeatedtamer', icon: npcGenericIcon}).bindTooltip('Defeated Tamer', {className: 'tooltip'}).addTo(map);
  defeatedtamer._icon.classList.add('defeatedtamer');
  markers.push(defeatedtamer);
  var mitotl = L.marker([833.47, 422.67], {title: 'mitotl', icon: npcCombatIcon}).bindTooltip('Mitotl', {className: 'tooltip'}).addTo(map);
  mitotl._icon.classList.add('mitotl');
  mitotl._icon.classList.add('combat');
  markers.push(mitotl);
  var atlatl = L.marker([833.47, 425.67], {title: 'atlatl', icon: npcCombatIcon}).bindTooltip('Atlatl', {className: 'tooltip'}).addTo(map);
  atlatl._icon.classList.add('atlatl');
  atlatl._icon.classList.add('combat');
  markers.push(atlatl);
  var dojominder = L.marker([833.47, 428.67], {title: 'dojominder', icon: npcMovingIcon}).bindTooltip('Dojo Minder', {className: 'tooltip'}).addTo(map);
  dojominder._icon.classList.add('dojominder');
  dojominder._icon.classList.add('moving');
  markers.push(dojominder);
  var cactonki = L.marker([833.47, 431.67], {title: 'cactonki', icon: npcCombatIcon}).bindTooltip('Cactonki', {className: 'tooltip'}).addTo(map);
  cactonki._icon.classList.add('cactonki');
  cactonki._icon.classList.add('combat');
  markers.push(cactonki);
  var cactonkiscompanion = L.marker([833.47, 434.67], {title: 'cactonkiscompanion', icon: npcCombatIcon}).bindTooltip("Cactonki's Companion", {className: 'tooltip'}).addTo(map);
  cactonkiscompanion._icon.classList.add('cactonkiscompanion');
  cactonkiscompanion._icon.classList.add('combat');
  markers.push(cactonkiscompanion);
  var tonali = L.marker([833.47, 437.67], {title: 'tonali', icon: npcCombatIcon}).bindTooltip('Tonali', {className: 'tooltip'}).addTo(map);
  tonali._icon.classList.add('tonali');
  tonali._icon.classList.add('combat');
  markers.push(tonali);
  var tonaliscompanion = L.marker([833.47, 440.67], {title: 'tonaliscompanion', icon: npcCombatIcon}).bindTooltip("Tonali's Companion??", {className: 'tooltip'}).addTo(map);
  tonaliscompanion._icon.classList.add('tonaliscompanion');
  tonaliscompanion._icon.classList.add('combat');
  markers.push(tonaliscompanion);
  var yareni = L.marker([836.47, 430.9], {title: 'yareni', icon: npcYareniIcon}).bindTooltip('Yareni', {className: 'tooltip'}).addTo(map);
  yareni._icon.classList.add('yareni');
  yareni._icon.classList.add('combat');
  markers.push(yareni);
  var paktli = L.marker([759.91, 407.79], {title: 'paktli', icon: npcClothingIcon}).bindTooltip('Paktli', {className: 'tooltip'}).addTo(map);
  paktli._icon.classList.add('paktli');
  paktli._icon.classList.add('clothing');
  markers.push(paktli);
  var taumafa = L.marker([759.91, 410.79], {title: 'taumafa', icon: npcGenericIcon}).bindTooltip('Taumafa', {className: 'tooltip'}).addTo(map);
  taumafa._icon.classList.add('taumafa');
  markers.push(taumafa);
  var cuitlatl = L.marker([763.16, 386.79], {title: 'cuitlatl', icon: npcGenericIcon}).bindTooltip('Cuitlatl', {className: 'tooltip'}).addTo(map);
  cuitlatl._icon.classList.add('cuitlatl');
  markers.push(cuitlatl);
  var izel = L.marker([763.41, 365.78], {title: 'izel', icon: npcGenericIcon}).bindTooltip('Izel', {className: 'tooltip'}).addTo(map);
  izel._icon.classList.add('izel');
  markers.push(izel);
  var quetzalianvendor = L.marker([728, 384.2], {title: 'quetzalianvendor', icon: npcVendorIcon}).bindTooltip('Quetzalian Vendor', {className: 'tooltip'}).addTo(map);
  quetzalianvendor._icon.classList.add('quetzalianvendor');
  quetzalianvendor._icon.classList.add('vendor');
  markers.push(quetzalianvendor);
  var yolotl = L.marker([728, 387.2], {title: 'yolotl', icon: npcGenericIcon}).bindTooltip('Yolotl', {className: 'tooltip'}).addTo(map);
  yolotl._icon.classList.add('yolotl');
  markers.push(yolotl);
  var teotl = L.marker([728, 390.2], {title: 'teotl', icon: npcGenericIcon}).bindTooltip('Teotl', {className: 'tooltip'}).addTo(map);
  teotl._icon.classList.add('teotl');
  markers.push(teotl);
  var tiredguard = L.marker([712.5, 357.07], {title: 'tiredguard', icon: npcGenericIcon}).bindTooltip('Tired Guard', {className: 'tooltip'}).addTo(map);
  tiredguard._icon.classList.add('tiredguard');
  markers.push(tiredguard);
  var stoicquetzalian = L.marker([708.5, 347.44], {title: 'stoicquetzalian', icon: npcGenericIcon}).bindTooltip('Stoic Quetzalian', {className: 'tooltip'}).addTo(map);
  stoicquetzalian._icon.classList.add('stoicquetzalian');
  markers.push(stoicquetzalian);
  var yaotzin = L.marker([692.08, 348.53], {title: 'yaotzin', icon: npcFurnitureIcon}).bindTooltip('Yaotzin', {className: 'tooltip'}).addTo(map);
  yaotzin._icon.classList.add('yaotzin');
  yaotzin._icon.classList.add('furniture');
  markers.push(yaotzin);
  var lidia = L.marker([692.08, 351.53], {title: 'lidia', icon: npcGenericIcon}).bindTooltip('Lidia', {className: 'tooltip'}).addTo(map);
  lidia._icon.classList.add('lidia');
  markers.push(lidia);
  var dayami = L.marker([692.08, 351.53], {title: 'dayami', icon: npcGenericIcon}).bindTooltip('Dayami', {className: 'tooltip'}).addTo(map);
  dayami._icon.classList.add('dayami');
  markers.push(dayami);
  var ollin = L.marker([686.83, 351.53], {title: 'ollin', icon: npcGenericIcon}).bindTooltip('Ollin', {className: 'tooltip'}).addTo(map);
  ollin._icon.classList.add('ollin');
  markers.push(ollin);
  var yuma = L.marker([686.83, 375.66], {title: 'yuma', icon: npcGenericIcon}).bindTooltip('Yuma', {className: 'tooltip'}).addTo(map);
  yuma._icon.classList.add('yuma');
  markers.push(yuma);
  var kiango = L.marker([674.08, 370.03], {title: 'kiango', icon: npcGenericIcon}).bindTooltip('Kiango', {className: 'tooltip'}).addTo(map);
  kiango._icon.classList.add('kiango');
  markers.push(kiango);
  var njema = L.marker([674.08, 375.03], {title: 'njema', icon: npcGenericIcon}).bindTooltip('Njema', {className: 'tooltip'}).addTo(map);
  njema._icon.classList.add('njema');
  markers.push(njema);
  var thimba = L.marker([667.58, 350.03], {title: 'thimba', icon: npcGenericIcon}).bindTooltip('Thimba', {className: 'tooltip'}).addTo(map);
  thimba._icon.classList.add('thimba');
  markers.push(thimba);
  var pipiyoli = L.marker([667.58, 353.03], {title: 'pipiyoli', icon: npcGenericIcon}).bindTooltip('Pipiyoli', {className: 'tooltip'}).addTo(map);
  pipiyoli._icon.classList.add('pipiyoli');
  markers.push(pipiyoli);
  var huitzilin = L.marker([671.21, 384.54], {title: 'huitzilin', icon: npcGenericIcon}).bindTooltip('Huitzilin', {className: 'tooltip'}).addTo(map);
  huitzilin._icon.classList.add('huitzilin');
  markers.push(huitzilin);
  var tlaicuilo = L.marker([741.12, 709.51], {title: 'tlaicuilo', icon: npcCombatIcon}).bindTooltip('Tlaicuilo', {className: 'tooltip'}).addTo(map);
  tlaicuilo._icon.classList.add('tlaicuilo');
  tlaicuilo._icon.classList.add('combat');
  markers.push(tlaicuilo);
  var chaustlil = L.marker([714.99, 731.39], {title: 'chaustlil', icon: npcCombatIcon}).bindTooltip('Chaustlil', {className: 'tooltip'}).addTo(map);
  chaustlil._icon.classList.add('chaustlil');
  chaustlil._icon.classList.add('combat');
  markers.push(chaustlil);
  var ailani = L.marker([740.99, 755.52], {title: 'ailani', icon: npcCombatIcon}).bindTooltip('Ailani', {className: 'tooltip'}).addTo(map);
  ailani._icon.classList.add('ailani');
  ailani._icon.classList.add('combat');
  markers.push(ailani);
  var gardenguardian = L.marker([732.75, 770.78], {title: 'gardenguardian', icon: npcCombatIcon}).bindTooltip('Gardenguardian', {className: 'tooltip'}).addTo(map);
  gardenguardian._icon.classList.add('gardenguardian');
  gardenguardian._icon.classList.add('combat');
  markers.push(gardenguardian);
  var gardenguardian2 = L.marker([732.75, 772.53], {title: 'gardenguardian2', icon: npcCombatIcon}).bindTooltip('Gardenguardian 2', {className: 'tooltip'}).addTo(map);
  gardenguardian2._icon.classList.add('gardenguardian2');
  gardenguardian2._icon.classList.add('combat');
  markers.push(gardenguardian2);
  var izamn = L.marker([737.13, 811.87], {title: 'izamn', icon: npcMovingCombatIcon}).bindTooltip('Izamná', {className: 'tooltip'}).addTo(map);
  izamn._icon.classList.add('izamn');
  izamn._icon.classList.add('moving');
  izamn._icon.classList.add('combat');
  markers.push(izamn);
  var tastelesscosplayer = L.marker([722.5, 831.24], {title: 'tastelesscosplayer', icon: npcCombatIcon}).bindTooltip('Tasteless Cosplayer', {className: 'tooltip'}).addTo(map);
  tastelesscosplayer._icon.classList.add('tastelesscosplayer');
  tastelesscosplayer._icon.classList.add('combat');
  markers.push(tastelesscosplayer);
  var tlateco = L.marker([750.5, 826.62], {title: 'tlateco', icon: npcCombatIcon}).bindTooltip('Tlateco', {className: 'tooltip'}).addTo(map);
  tlateco._icon.classList.add('tlateco');
  tlateco._icon.classList.add('combat');
  markers.push(tlateco);
  var centli = L.marker([693.32, 841.72], {title: 'centli', icon: npcCombatIcon}).bindTooltip('Centli', {className: 'tooltip'}).addTo(map);
  centli._icon.classList.add('centli');
  centli._icon.classList.add('combat');
  markers.push(centli);
  var ariam = L.marker([782.15, 845.85], {title: 'ariam', icon: npcCombatIcon}).bindTooltip('Ariam', {className: 'tooltip'}).addTo(map);
  ariam._icon.classList.add('ariam');
  ariam._icon.classList.add('combat');
  markers.push(ariam);
  var chizuka = L.marker([712.25, 877.61], {title: 'chizuka', icon: npcCombatIcon}).bindTooltip('Chizuka', {className: 'tooltip'}).addTo(map);
  chizuka._icon.classList.add('chizuka');
  chizuka._icon.classList.add('combat');
  markers.push(chizuka);
  var yoali = L.marker([765.89, 877.8], {title: 'yoali', icon: npcCombatIcon}).bindTooltip('Yoali', {className: 'tooltip'}).addTo(map);
  yoali._icon.classList.add('yoali');
  yoali._icon.classList.add('combat');
  markers.push(yoali);
  var soma = L.marker([736.64, 870.04], {title: 'soma', icon: npcCombatIcon}).bindTooltip('Soma', {className: 'tooltip'}).addTo(map);
  soma._icon.classList.add('soma');
  soma._icon.classList.add('combat');
  markers.push(soma);
  var spacedoutguard = L.marker([671.06, 405.47], {title: 'spacedoutguard', icon: npcGenericIcon}).bindTooltip('Spaced-Out Guard', {className: 'tooltip'}).addTo(map);
  spacedoutguard._icon.classList.add('spacedoutguard');
  markers.push(spacedoutguard);
  var offdutyguard = L.marker([668.06, 405.47], {title: 'offdutyguard', icon: npcGenericIcon}).bindTooltip('Off-Duty Guard', {className: 'tooltip'}).addTo(map);
  offdutyguard._icon.classList.add('offdutyguard');
  markers.push(offdutyguard);
  var chilledoutguard = L.marker([665.06, 405.47], {title: 'chilledoutguard', icon: npcGenericIcon}).bindTooltip('Chilled-Out Guard', {className: 'tooltip'}).addTo(map);
  chilledoutguard._icon.classList.add('chilledoutguard');
  markers.push(chilledoutguard);
  var kemal = L.marker([674.56, 447.48], {title: 'kemal', icon: npcGenericIcon}).bindTooltip('Kemal', {className: 'tooltip'}).addTo(map);
  kemal._icon.classList.add('kemal');
  markers.push(kemal);
  var retiredminer = L.marker([667.78, 460.24], {title: 'retiredminer', icon: npcGenericIcon}).bindTooltip('Retired Miner', {className: 'tooltip'}).addTo(map);
  retiredminer._icon.classList.add('retiredminer');
  markers.push(retiredminer);
  var smithsguardrep = L.marker([675.03, 468.87], {title: 'smithsguardrep', icon: npcGenericIcon}).bindTooltip("Smith's Guard Rep", {className: 'tooltip'}).addTo(map);
  smithsguardrep._icon.classList.add('smithsguardrep');
  markers.push(smithsguardrep);
  var guildmasterjatziri = L.marker([678.03, 468.87], {title: 'guildmasterjatziri', icon: npcGenericIcon}).bindTooltip('Guildmaster Jatziri', {className: 'tooltip'}).addTo(map);
  guildmasterjatziri._icon.classList.add('guildmasterjatziri');
  markers.push(guildmasterjatziri);
  var tepanahui = L.marker([675, 478.86], {title: 'tepanahui', icon: npcGenericIcon}).bindTooltip('Tepanahui', {className: 'tooltip'}).addTo(map);
  tepanahui._icon.classList.add('tepanahui');
  markers.push(tepanahui);
  var donaj = L.marker([675, 482.37], {title: 'donaj', icon: npcGenericIcon}).bindTooltip('Donaj', {className: 'tooltip'}).addTo(map);
  donaj._icon.classList.add('donaj');
  markers.push(donaj);
  var chantico = L.marker([677.5, 501.12], {title: 'chantico', icon: npcGenericIcon}).bindTooltip('Chantico', {className: 'tooltip'}).addTo(map);
  chantico._icon.classList.add('chantico');
  markers.push(chantico);
  var meztli = L.marker([684.75, 482.24], {title: 'meztli', icon: npcGenericIcon}).bindTooltip('Meztli', {className: 'tooltip'}).addTo(map);
  meztli._icon.classList.add('meztli');
  markers.push(meztli);
  var ollinkan = L.marker([716.18, 472.62], {title: 'ollinkan', icon: npcGenericIcon}).bindTooltip('Ollinkan', {className: 'tooltip'}).addTo(map);
  ollinkan._icon.classList.add('ollinkan');
  markers.push(ollinkan);
  var yoltic = L.marker([725.93, 470.62], {title: 'yoltic', icon: npcGenericIcon}).bindTooltip('Yoltic', {className: 'tooltip'}).addTo(map);
  yoltic._icon.classList.add('yoltic');
  markers.push(yoltic);
  var narrativedesigner = L.marker([728.93, 470.62], {title: 'narrativedesigner', icon: npcGenericIcon}).bindTooltip('Narrative Designer', {className: 'tooltip'}).addTo(map);
  narrativedesigner._icon.classList.add('narrativedesigner');
  markers.push(narrativedesigner);
  var xochipilli = L.marker([698.56, 438.36], {title: 'xochipilli', icon: npcGenericIcon}).bindTooltip('Xochipilli', {className: 'tooltip'}).addTo(map);
  xochipilli._icon.classList.add('xochipilli');
  markers.push(xochipilli);
  var xochitl = L.marker([699.93, 440.23], {title: 'xochitl', icon: npcGenericIcon}).bindTooltip('Xochitl', {className: 'tooltip'}).addTo(map);
  xochitl._icon.classList.add('xochitl');
  markers.push(xochitl);
  var tzopelli = L.marker([691.91, 413.7], {title: 'tzopelli', icon: npcGenericIcon}).bindTooltip('Tzopelli', {className: 'tooltip'}).addTo(map);
  tzopelli._icon.classList.add('tzopelli');
  markers.push(tzopelli);
  var generalx = L.marker([605.25, 335.97], {title: 'generalx', icon: npcGenericIcon}).bindTooltip('General X', {className: 'tooltip'}).addTo(map);
  generalx._icon.classList.add('generalx');
  markers.push(generalx);
  var ocelotl = L.marker([561.42, 403.86], {title: 'ocelotl', icon: npcGenericIcon}).bindTooltip('Ocelotl', {className: 'tooltip'}).addTo(map);
  ocelotl._icon.classList.add('ocelotl');
  markers.push(ocelotl);
  var miner = L.marker([552.17, 430.36], {title: 'miner', icon: npcCombatIcon}).bindTooltip('Miner', {className: 'tooltip'}).addTo(map);
  miner._icon.classList.add('miner');
  miner._icon.classList.add('combat');
  markers.push(miner);
  var alitzel = L.marker([551.59, 455.06], {title: 'alitzel', icon: npcGenericIcon}).bindTooltip('Alitzel', {className: 'tooltip'}).addTo(map);
  alitzel._icon.classList.add('alitzel');
  markers.push(alitzel);
  var technologist = L.marker([536.25, 419.71], {title: 'technologist', icon: npcMovingIcon}).bindTooltip('Technologist', {className: 'tooltip'}).addTo(map);
  technologist._icon.classList.add('technologist');
  technologist._icon.classList.add('moving');
  markers.push(technologist);
  var oxomoco = L.marker([527.75, 381.46], {title: 'oxomoco', icon: npcCombatIcon}).bindTooltip('Oxomoco', {className: 'tooltip'}).addTo(map);
  oxomoco._icon.classList.add('oxomoco');
  oxomoco._icon.classList.add('combat');
  markers.push(oxomoco);
  var angryminer = L.marker([510.5, 403.62], {title: 'angryminer', icon: npcCombatIcon}).bindTooltip('Angry Miner', {className: 'tooltip'}).addTo(map);
  angryminer._icon.classList.add('angryminer');
  angryminer._icon.classList.add('combat');
  markers.push(angryminer);
  var crystallographer = L.marker([513.31, 426.93], {title: 'crystallographer', icon: npcGenericIcon}).bindTooltip('Crystallographer', {className: 'tooltip'}).addTo(map);
  crystallographer._icon.classList.add('crystallographer');
  markers.push(crystallographer);
  var cluelessguard = L.marker([486.2, 395.06], {title: 'cluelessguard', icon: npcCombatIcon}).bindTooltip('Clueless Guard', {className: 'tooltip'}).addTo(map);
  cluelessguard._icon.classList.add('cluelessguard');
  cluelessguard._icon.classList.add('combat');
  markers.push(cluelessguard);
  var helplessguard = L.marker([486.2, 397], {title: 'helplessguard', icon: npcCombatIcon}).bindTooltip('Helpless Guard', {className: 'tooltip'}).addTo(map);
  helplessguard._icon.classList.add('helplessguard');
  helplessguard._icon.classList.add('combat');
  markers.push(helplessguard);
  var yuritzi = L.marker([488.34, 426.55], {title: 'yuritzi', icon: npcMovingCombatIcon}).bindTooltip('Yuritzi', {className: 'tooltip'}).addTo(map);
  yuritzi._icon.classList.add('yuritzi');
  yuritzi._icon.classList.add('moving');
  yuritzi._icon.classList.add('combat');
  markers.push(yuritzi);
  var losttourist = L.marker([455.4, 445.46], {title: 'losttourist', icon: npcCombatIcon}).bindTooltip('Lost Tourist', {className: 'tooltip'}).addTo(map);
  losttourist._icon.classList.add('losttourist');
  losttourist._icon.classList.add('combat');
  markers.push(losttourist);
  var xalli = L.marker([445.13, 411.24], {title: 'xalli', icon: npcCombatIcon}).bindTooltip('Xalli', {className: 'tooltip'}).addTo(map);
  xalli._icon.classList.add('xalli');
  xalli._icon.classList.add('combat');
  markers.push(xalli);
  var xalliscompanion = L.marker([442.88, 414.24], {title: 'xalliscompanion', icon: npcCombatIcon}).bindTooltip("Xalli's Companion", {className: 'tooltip'}).addTo(map);
  xalliscompanion._icon.classList.add('xalliscompanion');
  xalliscompanion._icon.classList.add('combat');
  markers.push(xalliscompanion);
  var meya = L.marker([419.38, 390.86], {title: 'meya', icon: npcCombatIcon}).bindTooltip('Meya', {className: 'tooltip'}).addTo(map);
  meya._icon.classList.add('meya');
  meya._icon.classList.add('combat');
  markers.push(meya);
  var meyascompanion = L.marker([422.13, 388.23], {title: 'meyascompanion', icon: npcCombatIcon}).bindTooltip("Meya's Companion", {className: 'tooltip'}).addTo(map);
  meyascompanion._icon.classList.add('meyascompanion');
  meyascompanion._icon.classList.add('combat');
  markers.push(meyascompanion);
  var crystaltemtemfan = L.marker([415.57, 419.28], {title: 'crystaltemtemfan', icon: npcCombatIcon}).bindTooltip('Crystal Temtem Fan', {className: 'tooltip'}).addTo(map);
  crystaltemtemfan._icon.classList.add('crystaltemtemfan');
  crystaltemtemfan._icon.classList.add('combat');
  markers.push(crystaltemtemfan);
  var crystaltemtemfan2 = L.marker([415.57, 421.91], {title: 'crystaltemtemfan2', icon: npcCombatIcon}).bindTooltip('Crystal Temtem Fan 2', {className: 'tooltip'}).addTo(map);
  crystaltemtemfan2._icon.classList.add('crystaltemtemfan2');
  crystaltemtemfan2._icon.classList.add('combat');
  markers.push(crystaltemtemfan2);
  var chauatl = L.marker([430.83, 446.91], {title: 'chauatl', icon: npcGenericIcon}).bindTooltip('Chauatl', {className: 'tooltip'}).addTo(map);
  chauatl._icon.classList.add('chauatl');
  markers.push(chauatl);
  var kin = L.marker([527.81, 459.86], {title: 'kin', icon: npcCombatIcon}).bindTooltip('Kin', {className: 'tooltip'}).addTo(map);
  kin._icon.classList.add('kin');
  kin._icon.classList.add('combat');
  markers.push(kin);
  var eso = L.marker([564.31, 492.08], {title: 'eso', icon: npcCombatIcon}).bindTooltip('Eso', {className: 'tooltip'}).addTo(map);
  eso._icon.classList.add('eso');
  eso._icon.classList.add('combat');
  markers.push(eso);
  var zazil = L.marker([578.22, 452.67], {title: 'zazil', icon: npcMovingIcon}).bindTooltip('Zazil', {className: 'tooltip'}).addTo(map);
  zazil._icon.classList.add('zazil');
  zazil._icon.classList.add('moving');
  markers.push(zazil);
  var kuautli = L.marker([593.72, 429.54], {title: 'kuautli', icon: npcCombatIcon}).bindTooltip('Kuautli', {className: 'tooltip'}).addTo(map);
  kuautli._icon.classList.add('kuautli');
  kuautli._icon.classList.add('combat');
  markers.push(kuautli);
  var offdutysmith = L.marker([578.09, 470.05], {title: 'offdutysmith', icon: npcCombatIcon}).bindTooltip('Off-Duty Smith', {className: 'tooltip'}).addTo(map);
  offdutysmith._icon.classList.add('offdutysmith');
  offdutysmith._icon.classList.add('combat');
  markers.push(offdutysmith);
  var offdutysmith2 = L.marker([581.45, 470.05], {title: 'offdutysmith2', icon: npcCombatIcon}).bindTooltip('Off-Duty Smith 2', {className: 'tooltip'}).addTo(map);
  offdutysmith2._icon.classList.add('offdutysmith2');
  offdutysmith2._icon.classList.add('combat');
  markers.push(offdutysmith2);
  var mayahuel = L.marker([599.06, 507.2], {title: 'mayahuel', icon: npcMovingIcon}).bindTooltip('Mayahuel', {className: 'tooltip'}).addTo(map);
  mayahuel._icon.classList.add('mayahuel');
  mayahuel._icon.classList.add('moving');
  markers.push(mayahuel);
  var chaak = L.marker([644.5, 565.73], {title: 'chaak', icon: npcGenericIcon}).bindTooltip('Chaak', {className: 'tooltip'}).addTo(map);
  chaak._icon.classList.add('chaak');
  markers.push(chaak);
  var tucmanicurator = L.marker([558.25, 600.11], {title: 'tucmanicurator', icon: npcMovingCombatIcon}).bindTooltip('Tucmani Curator', {className: 'tooltip'}).addTo(map);
  tucmanicurator._icon.classList.add('tucmanicurator');
  tucmanicurator._icon.classList.add('moving');
  tucmanicurator._icon.classList.add('combat');
  markers.push(tucmanicurator);
  var miffedminer = L.marker([578.56, 533.12], {title: 'miffedminer', icon: npcGenericIcon}).bindTooltip('Miffed Miner', {className: 'tooltip'}).addTo(map);
  miffedminer._icon.classList.add('miffedminer');
  markers.push(miffedminer);
  var veteranminer = L.marker([578.63, 530.99], {title: 'veteranminer', icon: npcGenericIcon}).bindTooltip('Veteran Miner', {className: 'tooltip'}).addTo(map);
  veteranminer._icon.classList.add('veteranminer');
  markers.push(veteranminer);
  var concernedminer = L.marker([577.31, 530.87], {title: 'concernedminer', icon: npcGenericIcon}).bindTooltip('Concerned Miner', {className: 'tooltip'}).addTo(map);
  concernedminer._icon.classList.add('concernedminer');
  markers.push(concernedminer);
  var exasperatedminer = L.marker([576.88, 532.56], {title: 'exasperatedminer', icon: npcGenericIcon}).bindTooltip('Exasperated Miner', {className: 'tooltip'}).addTo(map);
  exasperatedminer._icon.classList.add('exasperatedminer');
  markers.push(exasperatedminer);
  var imprudentminer = L.marker([576.88, 534.81], {title: 'imprudentminer', icon: npcGenericIcon}).bindTooltip('Imprudent Miner', {className: 'tooltip'}).addTo(map);
  imprudentminer._icon.classList.add('imprudentminer');
  markers.push(imprudentminer);
  var chaneki = L.marker([554.66, 522.31], {title: 'chaneki', icon: npcCombatIcon}).bindTooltip('Chaneki', {className: 'tooltip'}).addTo(map);
  chaneki._icon.classList.add('chaneki');
  chaneki._icon.classList.add('combat');
  markers.push(chaneki);
  var chanekiscompanion = L.marker([553.72, 520.75], {title: 'chanekiscompanion', icon: npcCombatIcon}).bindTooltip("Chaneki's Companion", {className: 'tooltip'}).addTo(map);
  chanekiscompanion._icon.classList.add('chanekiscompanion');
  chanekiscompanion._icon.classList.add('combat');
  markers.push(chanekiscompanion);
  var iyali = L.marker([513.44, 508.05], {title: 'iyali', icon: npcCombatIcon}).bindTooltip('Iyali', {className: 'tooltip'}).addTo(map);
  iyali._icon.classList.add('iyali');
  iyali._icon.classList.add('combat');
  markers.push(iyali);
  var quetzalianguard = L.marker([255.72, 313.17], {title: 'quetzalianguard', icon: npcGenericIcon}).bindTooltip('Quetzalian Guard', {className: 'tooltip'}).addTo(map);
  quetzalianguard._icon.classList.add('quetzalianguard');
  markers.push(quetzalianguard);
  var quetzalianguard = L.marker([255.85, 320.8], {title: 'quetzalianguard', icon: npcGenericIcon}).bindTooltip('Quetzalian Guard ', {className: 'tooltip'}).addTo(map);
  quetzalianguard._icon.classList.add('quetzalianguard');
  markers.push(quetzalianguard);
  var stallminder = L.marker([161.3, 286.15], {title: 'stallminder', icon: npcVendorIcon}).bindTooltip('Stall Minder', {className: 'tooltip'}).addTo(map);
  stallminder._icon.classList.add('stallminder');
  stallminder._icon.classList.add('vendor');
  markers.push(stallminder);
  var manki = L.marker([154.67, 291.65], {title: 'manki', icon: npcGenericIcon}).bindTooltip('Manki', {className: 'tooltip'}).addTo(map);
  manki._icon.classList.add('manki');
  markers.push(manki);
  var pinacatl = L.marker([102.97, 322.19], {title: 'pinacatl', icon: npcCombatIcon}).bindTooltip('Pinacatl', {className: 'tooltip'}).addTo(map);
  pinacatl._icon.classList.add('pinacatl');
  pinacatl._icon.classList.add('combat');
  markers.push(pinacatl);
  var chamatl = L.marker([100.22, 328.44], {title: 'chamatl', icon: npcCombatIcon}).bindTooltip('Chamatl', {className: 'tooltip'}).addTo(map);
  chamatl._icon.classList.add('chamatl');
  chamatl._icon.classList.add('combat');
  markers.push(chamatl);
  var hernn = L.marker([52.95, 334.15], {title: 'hernn', icon: npcCombatIcon}).bindTooltip('Hernán', {className: 'tooltip'}).addTo(map);
  hernn._icon.classList.add('hernn');
  hernn._icon.classList.add('combat');
  markers.push(hernn);
  var amitlatl = L.marker([48.95, 376.03], {title: 'amitlatl', icon: npcCombatIcon}).bindTooltip('Amitlatl', {className: 'tooltip'}).addTo(map);
  amitlatl._icon.classList.add('amitlatl');
  amitlatl._icon.classList.add('combat');
  markers.push(amitlatl);
  var amiyatzin = L.marker([48.95, 377.91], {title: 'amiyatzin', icon: npcCombatIcon}).bindTooltip('Amiyatzin', {className: 'tooltip'}).addTo(map);
  amiyatzin._icon.classList.add('amiyatzin');
  amiyatzin._icon.classList.add('combat');
  markers.push(amiyatzin);
  var lifeguard = L.marker([92.43, 295.25], {title: 'lifeguard', icon: npcCombatIcon}).bindTooltip('Lifeguard', {className: 'tooltip'}).addTo(map);
  lifeguard._icon.classList.add('lifeguard');
  lifeguard._icon.classList.add('combat');
  markers.push(lifeguard);
  var guardpatrol = L.marker([59.54, 277.05], {title: 'guardpatrol', icon: npcCombatIcon}).bindTooltip('Guard Patrol', {className: 'tooltip'}).addTo(map);
  guardpatrol._icon.classList.add('guardpatrol');
  guardpatrol._icon.classList.add('combat');
  markers.push(guardpatrol);
  var guardpatrol = L.marker([50.42, 285.8], {title: 'guardpatrol', icon: npcCombatIcon}).bindTooltip('Guard Patrol', {className: 'tooltip'}).addTo(map);
  guardpatrol._icon.classList.add('guardpatrol');
  guardpatrol._icon.classList.add('combat');
  markers.push(guardpatrol);
  var kisiwanrefugee = L.marker([58.04, 259.92], {title: 'kisiwanrefugee', icon: npcCombatIcon}).bindTooltip('Kisiwan Refugee', {className: 'tooltip'}).addTo(map);
  kisiwanrefugee._icon.classList.add('kisiwanrefugee');
  kisiwanrefugee._icon.classList.add('combat');
  markers.push(kisiwanrefugee);
  var exhaustedrefugee = L.marker([63.92, 250.29], {title: 'exhaustedrefugee', icon: npcCombatIcon}).bindTooltip('Exhausted Refugee', {className: 'tooltip'}).addTo(map);
  exhaustedrefugee._icon.classList.add('exhaustedrefugee');
  exhaustedrefugee._icon.classList.add('combat');
  markers.push(exhaustedrefugee);
  var maintenanceworker = L.marker([53.79, 240.54], {title: 'maintenanceworker', icon: npcGenericIcon}).bindTooltip('Maintenance Worker', {className: 'tooltip'}).addTo(map);
  maintenanceworker._icon.classList.add('maintenanceworker');
  markers.push(maintenanceworker);
  var tucmanirepresentative = L.marker([31.75, 210.6], {title: 'tucmanirepresentative', icon: npcGenericIcon}).bindTooltip('Tucmani representative', {className: 'tooltip'}).addTo(map);
  tucmanirepresentative._icon.classList.add('tucmanirepresentative');
  markers.push(tucmanirepresentative);
  var akihiro = L.marker([31.75, 213.6], {title: 'akihiro', icon: npcGenericIcon}).bindTooltip('Akihiro', {className: 'tooltip'}).addTo(map);
  akihiro._icon.classList.add('akihiro');
  markers.push(akihiro);
  var kupelelezavendor = L.marker([31.75, 216.6], {title: 'kupelelezavendor', icon: npcVendorIcon}).bindTooltip('Kupeleleza Vendor', {className: 'tooltip'}).addTo(map);
  kupelelezavendor._icon.classList.add('kupelelezavendor');
  kupelelezavendor._icon.classList.add('vendor');
  markers.push(kupelelezavendor);
  var resistancerepresentative = L.marker([33.75, 210.6], {title: 'resistancerepresentative', icon: npcGenericIcon}).bindTooltip('Resistance representative', {className: 'tooltip'}).addTo(map);
  resistancerepresentative._icon.classList.add('resistancerepresentative');
  markers.push(resistancerepresentative);
  var restlessrefugee = L.marker([33.75, 213.6], {title: 'restlessrefugee', icon: npcMovingIcon}).bindTooltip('Restless refugee', {className: 'tooltip'}).addTo(map);
  restlessrefugee._icon.classList.add('restlessrefugee');
  restlessrefugee._icon.classList.add('moving');
  markers.push(restlessrefugee);
  var kisiwanrepresentative = L.marker([33.75, 216.6], {title: 'kisiwanrepresentative', icon: npcGenericIcon}).bindTooltip('Kisiwan representative', {className: 'tooltip'}).addTo(map);
  kisiwanrepresentative._icon.classList.add('kisiwanrepresentative');
  markers.push(kisiwanrepresentative);
  var huenupan = L.marker([92.31, 243.3], {title: 'huenupan', icon: npcCombatIcon}).bindTooltip('Huenupan', {className: 'tooltip'}).addTo(map);
  huenupan._icon.classList.add('huenupan');
  huenupan._icon.classList.add('combat');
  markers.push(huenupan);
  var zulia = L.marker([93.19, 235.62], {title: 'zulia', icon: npcCombatIcon}).bindTooltip('Zulia', {className: 'tooltip'}).addTo(map);
  zulia._icon.classList.add('zulia');
  zulia._icon.classList.add('combat');
  markers.push(zulia);
  var yaba = L.marker([93.19, 234.37], {title: 'yaba', icon: npcGenericIcon}).bindTooltip('Yaba', {className: 'tooltip'}).addTo(map);
  yaba._icon.classList.add('yaba');
  markers.push(yaba);
  var valentina = L.marker([122.24, 131.27], {title: 'valentina', icon: npcCombatIcon}).bindTooltip('Valentina', {className: 'tooltip'}).addTo(map);
  valentina._icon.classList.add('valentina');
  valentina._icon.classList.add('combat');
  markers.push(valentina);
  var federico = L.marker([122.24, 129.08], {title: 'federico', icon: npcCombatIcon}).bindTooltip('Federico', {className: 'tooltip'}).addTo(map);
  federico._icon.classList.add('federico');
  federico._icon.classList.add('combat');
  markers.push(federico);
  var tochtli = L.marker([161.4, 224.78], {title: 'tochtli', icon: npcMovingCombatIcon}).bindTooltip('Tochtli', {className: 'tooltip'}).addTo(map);
  tochtli._icon.classList.add('tochtli');
  tochtli._icon.classList.add('moving');
  tochtli._icon.classList.add('combat');
  markers.push(tochtli);
  var seniorrockhopper = L.marker([144.14, 272.73], {title: 'seniorrockhopper', icon: npcGenericIcon}).bindTooltip('Senior Rockhopper', {className: 'tooltip'}).addTo(map);
  seniorrockhopper._icon.classList.add('seniorrockhopper');
  markers.push(seniorrockhopper);
  var tetzauyo = L.marker([147.14, 272.73], {title: 'tetzauyo', icon: npcGenericIcon}).bindTooltip('Tetzauyo', {className: 'tooltip'}).addTo(map);
  tetzauyo._icon.classList.add('tetzauyo');
  markers.push(tetzauyo);
  var youngrockhopper = L.marker([150.14, 272.73], {title: 'youngrockhopper', icon: npcGenericIcon}).bindTooltip('Young Rockhopper', {className: 'tooltip'}).addTo(map);
  youngrockhopper._icon.classList.add('youngrockhopper');
  markers.push(youngrockhopper);
  var naolin = L.marker([313.49, 396.15], {title: 'naolin', icon: npcCombatIcon}).bindTooltip('Naolin', {className: 'tooltip'}).addTo(map);
  naolin._icon.classList.add('naolin');
  naolin._icon.classList.add('combat');
  markers.push(naolin);
  var tucmanichemist = L.marker([153.42, 408.46], {title: 'tucmanichemist', icon: npcCombatIcon}).bindTooltip('Tucmani Chemist', {className: 'tooltip'}).addTo(map);
  tucmanichemist._icon.classList.add('tucmanichemist');
  tucmanichemist._icon.classList.add('combat');
  markers.push(tucmanichemist);
  var guardplatoon = L.marker([201.53, 427.64], {title: 'guardplatoon', icon: npcCombatIcon}).bindTooltip('Guard Platoon', {className: 'tooltip'}).addTo(map);
  guardplatoon._icon.classList.add('guardplatoon');
  guardplatoon._icon.classList.add('combat');
  markers.push(guardplatoon);
  var guardplatoon = L.marker([201.53, 429.45], {title: 'guardplatoon', icon: npcCombatIcon}).bindTooltip('Guard Platoon', {className: 'tooltip'}).addTo(map);
  guardplatoon._icon.classList.add('guardplatoon');
  guardplatoon._icon.classList.add('combat');
  markers.push(guardplatoon);
  var restlessguard = L.marker([197.56, 485.18], {title: 'restlessguard', icon: npcCombatIcon}).bindTooltip('Restless Guard', {className: 'tooltip'}).addTo(map);
  restlessguard._icon.classList.add('restlessguard');
  restlessguard._icon.classList.add('combat');
  markers.push(restlessguard);
  var innocentquetzalian = L.marker([176.37, 510.27], {title: 'innocentquetzalian', icon: npcMovingCombatIcon}).bindTooltip('Innocent Quetzalian', {className: 'tooltip'}).addTo(map);
  innocentquetzalian._icon.classList.add('innocentquetzalian');
  innocentquetzalian._icon.classList.add('moving');
  innocentquetzalian._icon.classList.add('combat');
  markers.push(innocentquetzalian);
  var diligentguard = L.marker([153.42, 532.57], {title: 'diligentguard', icon: npcCombatIcon}).bindTooltip('Diligent Guard', {className: 'tooltip'}).addTo(map);
  diligentguard._icon.classList.add('diligentguard');
  diligentguard._icon.classList.add('combat');
  markers.push(diligentguard);
  var lonelywanderer = L.marker([176.69, 564.87], {title: 'lonelywanderer', icon: npcCombatIcon}).bindTooltip('Lonely Wanderer', {className: 'tooltip'}).addTo(map);
  lonelywanderer._icon.classList.add('lonelywanderer');
  lonelywanderer._icon.classList.add('combat');
  markers.push(lonelywanderer);
  var sugey = L.marker([134.81, 571.29], {title: 'sugey', icon: npcGenericIcon}).bindTooltip('Sugey', {className: 'tooltip'}).addTo(map);
  sugey._icon.classList.add('sugey');
  markers.push(sugey);
  var sugeyslabassitant = L.marker([143.94, 585.17], {title: 'sugeyslabassitant', icon: npcGenericIcon}).bindTooltip("Sugey's Lab Assitant", {className: 'tooltip'}).addTo(map);
  sugeyslabassitant._icon.classList.add('sugeyslabassitant');
  markers.push(sugeyslabassitant);
  var tokatl = L.marker([75.84, 617.24], {title: 'tokatl', icon: npcCombatIcon}).bindTooltip('Tokatl', {className: 'tooltip'}).addTo(map);
  tokatl._icon.classList.add('tokatl');
  tokatl._icon.classList.add('combat');
  markers.push(tokatl);
  var tlaloc = L.marker([77.34, 623.12], {title: 'tlaloc', icon: npcGenericIcon}).bindTooltip('Tlaloc', {className: 'tooltip'}).addTo(map);
  tlaloc._icon.classList.add('tlaloc');
  markers.push(tlaloc);
  var surfacesurvivor = L.marker([217.49, 663.86], {title: 'surfacesurvivor', icon: npcGenericIcon}).bindTooltip('Surface Survivor', {className: 'tooltip'}).addTo(map);
  surfacesurvivor._icon.classList.add('surfacesurvivor');
  markers.push(surfacesurvivor);
  var ledgesentinel = L.marker([231.59, 648.11], {title: 'ledgesentinel', icon: npcCombatIcon}).bindTooltip('Ledge Sentinel', {className: 'tooltip'}).addTo(map);
  ledgesentinel._icon.classList.add('ledgesentinel');
  ledgesentinel._icon.classList.add('combat');
  markers.push(ledgesentinel);
  var coscatl = L.marker([232.59, 656.61], {title: 'coscatl', icon: npcGenericIcon}).bindTooltip('Coscatl', {className: 'tooltip'}).addTo(map);
  coscatl._icon.classList.add('coscatl');
  markers.push(coscatl);
  var bonfirekeeper = L.marker([235.47, 675.74], {title: 'bonfirekeeper', icon: npcGenericIcon}).bindTooltip('Bonfire Keeper', {className: 'tooltip'}).addTo(map);
  bonfirekeeper._icon.classList.add('bonfirekeeper');
  markers.push(bonfirekeeper);
  var ixtab = L.marker([231.09, 688.12], {title: 'ixtab', icon: npcGenericIcon}).bindTooltip('Ixtab', {className: 'tooltip'}).addTo(map);
  ixtab._icon.classList.add('ixtab');
  markers.push(ixtab);
  var atl = L.marker([240.1, 653.11], {title: 'atl', icon: npcGenericIcon}).bindTooltip('Atl', {className: 'tooltip'}).addTo(map);
  atl._icon.classList.add('atl');
  markers.push(atl);
  var astitok = L.marker([251.6, 667.11], {title: 'astitok', icon: npcGenericIcon}).bindTooltip('Astitok', {className: 'tooltip'}).addTo(map);
  astitok._icon.classList.add('astitok');
  markers.push(astitok);
  var tlauili = L.marker([251.98, 681.62], {title: 'tlauili', icon: npcGenericIcon}).bindTooltip('Tlauili', {className: 'tooltip'}).addTo(map);
  tlauili._icon.classList.add('tlauili');
  markers.push(tlauili);
  var tototl = L.marker([254.98, 681.62], {title: 'tototl', icon: npcGenericIcon}).bindTooltip('Tototl', {className: 'tooltip'}).addTo(map);
  tototl._icon.classList.add('tototl');
  markers.push(tototl);
  var iztac = L.marker([237.6, 696.12], {title: 'iztac', icon: npcGenericIcon}).bindTooltip('Iztac', {className: 'tooltip'}).addTo(map);
  iztac._icon.classList.add('iztac');
  markers.push(iztac);
  var tecolli = L.marker([240.6, 696.12], {title: 'tecolli', icon: npcGenericIcon}).bindTooltip('Tecolli', {className: 'tooltip'}).addTo(map);
  tecolli._icon.classList.add('tecolli');
  markers.push(tecolli);
  var macuil = L.marker([243.6, 696.12], {title: 'macuil', icon: npcGenericIcon}).bindTooltip('Macuil', {className: 'tooltip'}).addTo(map);
  macuil._icon.classList.add('macuil');
  markers.push(macuil);
  var elizabeth = L.marker([246.6, 696.12], {title: 'elizabeth', icon: npcGenericIcon}).bindTooltip('Elizabeth', {className: 'tooltip'}).addTo(map);
  elizabeth._icon.classList.add('elizabeth');
  markers.push(elizabeth);
  var sugeysintern = L.marker([192.87, 621.21], {title: 'sugeysintern', icon: npcCombatIcon}).bindTooltip("Sugey's Intern", {className: 'tooltip'}).addTo(map);
  sugeysintern._icon.classList.add('sugeysintern');
  sugeysintern._icon.classList.add('combat');
  markers.push(sugeysintern);
  var shywannabe = L.marker([227.72, 608.03], {title: 'shywannabe', icon: npcCombatIcon}).bindTooltip('Shy Wannabe', {className: 'tooltip'}).addTo(map);
  shywannabe._icon.classList.add('shywannabe');
  shywannabe._icon.classList.add('combat');
  markers.push(shywannabe);
  var quetzalianteenboy = L.marker([230.22, 598.03], {title: 'quetzalianteenboy', icon: npcCombatIcon}).bindTooltip('Quetzalian Teen Boy', {className: 'tooltip'}).addTo(map);
  quetzalianteenboy._icon.classList.add('quetzalianteenboy');
  quetzalianteenboy._icon.classList.add('combat');
  markers.push(quetzalianteenboy);
  var cockywannabe = L.marker([229.97, 620.66], {title: 'cockywannabe', icon: npcCombatIcon}).bindTooltip('Cocky Wannabe', {className: 'tooltip'}).addTo(map);
  cockywannabe._icon.classList.add('cockywannabe');
  cockywannabe._icon.classList.add('combat');
  markers.push(cockywannabe);
  var quetzalianteengirl = L.marker([238.1, 608.65], {title: 'quetzalianteengirl', icon: npcCombatIcon}).bindTooltip('Quetzalian Teen Girl', {className: 'tooltip'}).addTo(map);
  quetzalianteengirl._icon.classList.add('quetzalianteengirl');
  quetzalianteengirl._icon.classList.add('combat');
  markers.push(quetzalianteengirl);
  var tucmanibotanist = L.marker([263.49, 616.13], {title: 'tucmanibotanist', icon: npcCombatIcon}).bindTooltip('Tucmani Botanist', {className: 'tooltip'}).addTo(map);
  tucmanibotanist._icon.classList.add('tucmanibotanist');
  tucmanibotanist._icon.classList.add('combat');
  markers.push(tucmanibotanist);
  var cluelessscout = L.marker([257.23, 535.23], {title: 'cluelessscout', icon: npcCombatIcon}).bindTooltip('Clueless Scout ', {className: 'tooltip'}).addTo(map);
  cluelessscout._icon.classList.add('cluelessscout');
  cluelessscout._icon.classList.add('combat');
  markers.push(cluelessscout);
  var elderlytucmani = L.marker([257.85, 487.85], {title: 'elderlytucmani', icon: npcGenericIcon}).bindTooltip('Elderly Tucmani', {className: 'tooltip'}).addTo(map);
  elderlytucmani._icon.classList.add('elderlytucmani');
  markers.push(elderlytucmani);
  var scaredexcursionist = L.marker([294.65, 536.49], {title: 'scaredexcursionist', icon: npcCombatIcon}).bindTooltip('Scared Excursionist', {className: 'tooltip'}).addTo(map);
  scaredexcursionist._icon.classList.add('scaredexcursionist');
  scaredexcursionist._icon.classList.add('combat');
  markers.push(scaredexcursionist);
  var levelheadedexcursionist = L.marker([293.15, 539.24], {title: 'levelheadedexcursionist', icon: npcCombatIcon}).bindTooltip('Level-Headed Excursionist', {className: 'tooltip'}).addTo(map);
  levelheadedexcursionist._icon.classList.add('levelheadedexcursionist');
  levelheadedexcursionist._icon.classList.add('combat');
  markers.push(levelheadedexcursionist);
  var waysidebandit = L.marker([335.61, 514.73], {title: 'waysidebandit', icon: npcCombatIcon}).bindTooltip('Wayside Bandit', {className: 'tooltip'}).addTo(map);
  waysidebandit._icon.classList.add('waysidebandit');
  waysidebandit._icon.classList.add('combat');
  markers.push(waysidebandit);
  var waysidebandit2 = L.marker([335.61, 517.11], {title: 'waysidebandit2', icon: npcCombatIcon}).bindTooltip('Wayside Bandit 2', {className: 'tooltip'}).addTo(map);
  waysidebandit2._icon.classList.add('waysidebandit2');
  waysidebandit2._icon.classList.add('combat');
  markers.push(waysidebandit2);
  var marauder = L.marker([283.38, 591.17], {title: 'marauder', icon: npcCombatIcon}).bindTooltip('Marauder', {className: 'tooltip'}).addTo(map);
  marauder._icon.classList.add('marauder');
  marauder._icon.classList.add('combat');
  markers.push(marauder);
  var marauder2 = L.marker([283.38, 593.92], {title: 'marauder2', icon: npcCombatIcon}).bindTooltip('Marauder 2', {className: 'tooltip'}).addTo(map);
  marauder2._icon.classList.add('marauder2');
  marauder2._icon.classList.add('combat');
  markers.push(marauder2);
  var lostexplorer = L.marker([281, 602.17], {title: 'lostexplorer', icon: npcMovingCombatIcon}).bindTooltip('Lost Explorer', {className: 'tooltip'}).addTo(map);
  lostexplorer._icon.classList.add('lostexplorer');
  lostexplorer._icon.classList.add('moving');
  lostexplorer._icon.classList.add('combat');
  markers.push(lostexplorer);
  var levi = L.marker([358.05, 780.74], {title: 'levi', icon: npcGenericIcon}).bindTooltip('Levi', {className: 'tooltip'}).addTo(map);
  levi._icon.classList.add('levi');
  markers.push(levi);
  var mixcatl = L.marker([355.8, 783.74], {title: 'mixcatl', icon: npcGenericIcon}).bindTooltip('Mixcóatl', {className: 'tooltip'}).addTo(map);
  mixcatl._icon.classList.add('mixcatl');
  markers.push(mixcatl);
  var tiredscavenger = L.marker([222.58, 694.81], {title: 'tiredscavenger', icon: npcGenericIcon}).bindTooltip('Tired Scavenger', {className: 'tooltip'}).addTo(map);
  tiredscavenger._icon.classList.add('tiredscavenger');
  markers.push(tiredscavenger);
  var scavengersentinel = L.marker([230.96, 718.56], {title: 'scavengersentinel', icon: npcCombatIcon}).bindTooltip('Scavenger Sentinel', {className: 'tooltip'}).addTo(map);
  scavengersentinel._icon.classList.add('scavengersentinel');
  scavengersentinel._icon.classList.add('combat');
  markers.push(scavengersentinel);
  var resentfulscavenger = L.marker([275.85, 789.37], {title: 'resentfulscavenger', icon: npcCombatIcon}).bindTooltip('Resentful Scavenger', {className: 'tooltip'}).addTo(map);
  resentfulscavenger._icon.classList.add('resentfulscavenger');
  resentfulscavenger._icon.classList.add('combat');
  markers.push(resentfulscavenger);
  var wannabeceleb = L.marker([279.48, 670.48], {title: 'wannabeceleb', icon: npcCombatIcon}).bindTooltip('Wannabe Celeb', {className: 'tooltip'}).addTo(map);
  wannabeceleb._icon.classList.add('wannabeceleb');
  wannabeceleb._icon.classList.add('combat');
  markers.push(wannabeceleb);
  var rapaciousscavenger = L.marker([208.73, 775.86], {title: 'rapaciousscavenger', icon: npcCombatIcon}).bindTooltip('Rapacious Scavenger', {className: 'tooltip'}).addTo(map);
  rapaciousscavenger._icon.classList.add('rapaciousscavenger');
  rapaciousscavenger._icon.classList.add('combat');
  markers.push(rapaciousscavenger);
  var mercilessscavenger = L.marker([203.6, 770.61], {title: 'mercilessscavenger', icon: npcCombatIcon}).bindTooltip('Merciless Scavenger', {className: 'tooltip'}).addTo(map);
  mercilessscavenger._icon.classList.add('mercilessscavenger');
  mercilessscavenger._icon.classList.add('combat');
  markers.push(mercilessscavenger);
  var hatefulscavenger = L.marker([209.11, 745.73], {title: 'hatefulscavenger', icon: npcCombatIcon}).bindTooltip('Hateful Scavenger', {className: 'tooltip'}).addTo(map);
  hatefulscavenger._icon.classList.add('hatefulscavenger');
  hatefulscavenger._icon.classList.add('combat');
  markers.push(hatefulscavenger);
  var aggrievedscavenger = L.marker([187.12, 724.95], {title: 'aggrievedscavenger', icon: npcCombatIcon}).bindTooltip('Aggrieved Scavenger', {className: 'tooltip'}).addTo(map);
  aggrievedscavenger._icon.classList.add('aggrievedscavenger');
  aggrievedscavenger._icon.classList.add('combat');
  markers.push(aggrievedscavenger);
  var slyscavenger = L.marker([168.39, 687.08], {title: 'slyscavenger', icon: npcCombatIcon}).bindTooltip('Sly Scavenger', {className: 'tooltip'}).addTo(map);
  slyscavenger._icon.classList.add('slyscavenger');
  slyscavenger._icon.classList.add('combat');
  markers.push(slyscavenger);
  var ambushingbandit = L.marker([155.64, 759.41], {title: 'ambushingbandit', icon: npcCombatIcon}).bindTooltip('Ambushing Bandit', {className: 'tooltip'}).addTo(map);
  ambushingbandit._icon.classList.add('ambushingbandit');
  ambushingbandit._icon.classList.add('combat');
  markers.push(ambushingbandit);
  var tricksterbandit = L.marker([155.76, 747.79], {title: 'tricksterbandit', icon: npcCombatIcon}).bindTooltip('Trickster Bandit', {className: 'tooltip'}).addTo(map);
  tricksterbandit._icon.classList.add('tricksterbandit');
  tricksterbandit._icon.classList.add('combat');
  markers.push(tricksterbandit);
  var scavengerscout = L.marker([123.92, 692.08], {title: 'scavengerscout', icon: npcCombatIcon}).bindTooltip('Scavenger Scout', {className: 'tooltip'}).addTo(map);
  scavengerscout._icon.classList.add('scavengerscout');
  scavengerscout._icon.classList.add('combat');
  markers.push(scavengerscout);
  var avidwrecker = L.marker([109.79, 713.83], {title: 'avidwrecker', icon: npcMovingCombatIcon}).bindTooltip('Avid Wrecker', {className: 'tooltip'}).addTo(map);
  avidwrecker._icon.classList.add('avidwrecker');
  avidwrecker._icon.classList.add('moving');
  avidwrecker._icon.classList.add('combat');
  markers.push(avidwrecker);
  var cruelscavenger = L.marker([136.63, 768.14], {title: 'cruelscavenger', icon: npcCombatIcon}).bindTooltip('Cruel Scavenger', {className: 'tooltip'}).addTo(map);
  cruelscavenger._icon.classList.add('cruelscavenger');
  cruelscavenger._icon.classList.add('combat');
  markers.push(cruelscavenger);
  var cruelscavenger2 = L.marker([136.63, 772.39], {title: 'cruelscavenger2', icon: npcCombatIcon}).bindTooltip('Cruel Scavenger 2', {className: 'tooltip'}).addTo(map);
  cruelscavenger2._icon.classList.add('cruelscavenger2');
  cruelscavenger2._icon.classList.add('combat');
  markers.push(cruelscavenger2);
  var elderlyexile = L.marker([144.36, 789.62], {title: 'elderlyexile', icon: npcMovingIcon}).bindTooltip('Elderly Exile', {className: 'tooltip'}).addTo(map);
  elderlyexile._icon.classList.add('elderlyexile');
  elderlyexile._icon.classList.add('moving');
  markers.push(elderlyexile);
  var sonofcrystalacolyte = L.marker([190.61, 837.55], {title: 'sonofcrystalacolyte', icon: npcCrystalGuardIcon}).bindTooltip('Son of Crystal Acolyte', {className: 'tooltip'}).addTo(map);
  sonofcrystalacolyte._icon.classList.add('sonofcrystalacolyte');
  sonofcrystalacolyte._icon.classList.add('combat');
  markers.push(sonofcrystalacolyte);
  var sonofcrystalzealot = L.marker([199.37, 826.05], {title: 'sonofcrystalzealot', icon: npcCrystalGuardIcon}).bindTooltip('Son of Crystal Zealot', {className: 'tooltip'}).addTo(map);
  sonofcrystalzealot._icon.classList.add('sonofcrystalzealot');
  sonofcrystalzealot._icon.classList.add('combat');
  markers.push(sonofcrystalzealot);
  var sonofcrystalbeliever = L.marker([208, 837.8], {title: 'sonofcrystalbeliever', icon: npcCrystalGuardIcon}).bindTooltip('Son of Crystal Believer', {className: 'tooltip'}).addTo(map);
  sonofcrystalbeliever._icon.classList.add('sonofcrystalbeliever');
  sonofcrystalbeliever._icon.classList.add('combat');
  markers.push(sonofcrystalbeliever);
  var chahuatl = L.marker([199.12, 837.05], {title: 'chahuatl', icon: npcCrystalGuardIcon}).bindTooltip('Chahuatl', {className: 'tooltip'}).addTo(map);
  chahuatl._icon.classList.add('chahuatl');
  chahuatl._icon.classList.add('combat');
  markers.push(chahuatl);
  
  // Use the tool over at https://codepen.io/susanpallmann/full/eYzbOyJ to format entries easier!
  
  //var name = L.marker([00, 00], {title: name, icon: npcGenericIcon}).bindTooltip("name", {className: 'tooltip'}).addTo(map);
  //name._icon.classList.add("testclass");
  //markers.push(name);
  
  function listSearchResults(query) {
    $('#results').empty();
    var counter = 0; 
    for (var i in markers){
      if (counter <= 4) {
        var markerID = markers[i].options.title;
        var markerToolTip = markers[i].getTooltip();
        var content = markerToolTip.getContent();
        var source = markers[i].options.icon.options.iconUrl;
        if (markerID.includes(query)){
          counter += 1;
          $('#results').append('<li><a href="" class="result-link" id="' + markerID + '"><img class="marker-small" src="' + source + '" alt="" /><p>' + content + '</p></a></li>');
        }
      }
    }
  }
  
  function refreshSearch(query) {
    $('.leaflet-marker-icon').addClass('hidden-icon');
    $('*[class*=' + query + ']').removeClass('hidden-icon');
  }
  
  $("#search").bind('input', function(){
    let value = $("#search").val();
    value = value.replace(/[^a-z0-9\s]/gi, '').replace(/[_\s]/g, '').toLowerCase();
    if (value === '') {
      $('.leaflet-marker-icon').removeClass('hidden-icon');
      $('#results').empty();
    } else {
      refreshSearch(value);
      listSearchResults(value);
    }
  });
  
  $('input[type="checkbox"]').bind('input', function(){
    $('.leaflet-marker-icon').addClass('hidden-icon');
    if ($('input:checkbox:checked').length) {
      $('input:checkbox:checked').each(function(index) {
        let key = $(this).val();
        console.log(key);
        $('.' + key).removeClass('hidden-icon');
      });
    } else {
      $('.leaflet-marker-icon').removeClass('hidden-icon');
    }
  });
});

$(document).on('click','.result-link',function(e){
  function markerFunction(id){
    for (var i in markers){
      var markerID = markers[i].options.title;
      if (markerID === id){
        markers[i].openTooltip();
        map.panTo(markers[i].getLatLng());
      } else {
        markers[i].closeTooltip();
      }
    }
  }
  markerFunction($(this).attr('id'));
  e.preventDefault();
}); 
